### PR TITLE
[TUTORIAL] Adds speak aloud step

### LINKED ISSUE #2765: [CONTENT] Explain read aloud in the tutorial?
It is a cool feature!

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we add an additional step to the user tutorial explaining the speak aloud functionality. We add this step between the run explanation and the next level explanation, translations are added for both English and Dutch.

**Fixes**
This PR fixes #2765.

**How to test**
Make sure you are logged in and navigate to `/tutorial`. Verify that there is a new step after the "run step", explaining the speak aloud functionality.

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks! But it seems that the read-aloud step does not highlight the dropdown?

image

**Comment by TiBiBa** [comment]
> Thanks! But it seems that the read-aloud step does not highlight the dropdown?
> 
> 
> 
> image
> 
> 

Weird! Might be a typescript issue, is it fixed if you update the bundles?

**Comment by TiBiBa** [comment]
Just tried it with updated bundles and it all seems to work for me:
Schermafbeelding 2022-05-23 om 13 40 23

**Comment by Felienne** [comment]
Hi @TiBiBa!

I have been seeing this weird text already a few times in the tutorial, before this PR also but maybe you can look into it? I though it was due to babel (which I am often too lazy to compile) but I am sure I ran it this time:

image

**Comment by TiBiBa** [comment]
> Hi @TiBiBa!
> 
> 
> 
> I have been seeing this weird text in the coding block already a few times in the tutorial, before this PR also but maybe you can look into it? I though it was due to babel (which I am often too lazy to compile) but I am sure I ran it this time:
> 
> 
> 
> image
> 
> 
> 
> 

Did you run it with the -f parameter? Will look into this!

**Comment by Felienne** [comment]
> > Hi @TiBiBa!
> > I have been seeing this weird text in the coding block already a few times in the tutorial, before this PR also but maybe you can look into it? I though it was due to babel (which I am often too lazy to compile) but I am sure I ran it this time:
> > image
> 
> Did you run it with the -f parameter? Will look into this!

I used:

image

**Comment by Felienne** [comment]
> > > Hi @TiBiBa!
> > > I have been seeing this weird text in the coding block already a few times in the tutorial, before this PR also but maybe you can look into it? I though it was due to babel (which I am often too lazy to compile) but I am sure I ran it this time:
> > > image
> > 
> > 
> > Did you run it with the -f parameter? Will look into this!
> 
> I used:
> 
> image

It seems to happen at least for Polish (not for English)

**Comment by TiBiBa** [comment]
> > > > Hi @TiBiBa!
> > > > I have been seeing this weird text in the coding block already a few times in the tutorial, before this PR also but maybe you can look into it? I though it was due to babel (which I am often too lazy to compile) but I am sure I ran it this time:
> > > > image
> > > 
> > > 
> > > Did you run it with the -f parameter? Will look into this!
> > 
> > 
> > I used:
> > image
> 
> It seems to happen at least for Polish (not for English)



> > > > Hi @TiBiBa!
> > > > I have been seeing this weird text in the coding block already a few times in the tutorial, before this PR also but maybe you can look into it? I though it was due to babel (which I am often too lazy to compile) but I am sure I ran it this time:
> > > > image
> > > 
> > > 
> > > Did you run it with the -f parameter? Will look into this!
> > 
> > 
> > I used:
> > image
> 
> It seems to happen at least for Polish (not for English)

That's because Weblate is not up-to-date yet with our latest changes. When it is all .po files without translations are automatically filled with the English translations. As they are not yet some fields are marked as "Fuzzy" and Babel guesses the best translation based on other translations already made for that languages -> return incorrect string. This issue should be solved when we merge this to main and Weblate created a PR filling all non-english/dutch .po files with the English translations.

**Comment by Felienne** [comment]
> > > > > Hi @TiBiBa!
> > > > > I have been seeing this weird text in the coding block already a few times in the tutorial, before this PR also but maybe you can look into it? I though it was due to babel (which I am often too lazy to compile) but I am sure I ran it this time:
> > > > > image
> > > > 
> > > > 
> > > > Did you run it with the -f parameter? Will look into this!
> > > 
> > > 
> > > I used:
> > > image
> > 
> > 
> > It seems to happen at least for Polish (not for English)
> 
> > > > > Hi @TiBiBa!
> > > > > I have been seeing this weird text in the coding block already a few times in the tutorial, before this PR also but maybe you can look into it? I though it was due to babel (which I am often too lazy to compile) but I am sure I ran it this time:
> > > > > image
> > > > 
> > > > 
> > > > Did you run it with the -f parameter? Will look into this!
> > > 
> > > 
> > > I used:
> > > image
> > 
> > 
> > It seems to happen at least for Polish (not for English)
> 
> That's because Weblate is not up-to-date yet with our latest changes. When it is all .po files without translations are automatically filled with the English translations. As they are not yet some fields are marked as "Fuzzy" and Babel guesses the best translation based on other translations already made for that languages -> return incorrect string. This issue should be solved when we merge this to main and Weblate created a PR filling all non-english/dutch .po files with the English translations.

ok, got it!

Regarding this PR, could we add another "run the code" step after selecting the read aloud so kids can immediately try it?

**Review by Felienne — CHANGES_REQUESTED** [review]
Could we add another "run the code" step after selecting the read aloud so kids can immediately try it? We can do that in a separate PR also, but since this has conflicts I could not merge it anyway (otherwise I would have!)

**Comment by TiBiBa** [comment]
Hi @Felienne, the speak aloud extra run function is fixed!

**Review by Felienne — APPROVED** [review]
Great!!

**Pull request merged**
