### PR TITLE
[BUG FIX] 'error or empty' achievement can be achieved again

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
This PR fixes an issue where we dependent on an unused variable in the TypeScript code for the 'error or empty' achievement check. Therefore it was never reached; and users where unable to achieve it. Thanks to an observant Hedy user (Kuno) this bug was noted.

**Fixes**
No related issue.

**How to test**
Make sure you have an account that doesn't have the 'error or empty' achievement yet. Create a program without an input but that is an actual program! For example, by using an `ask` without an `echo` in level 1. Verify that the achieved is received.

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @TiBiBa 

I have not yet managed to get the achievement again :( 

image

**Comment by TiBiBa** [comment]
> Hi @TiBiBa
> 
> I have not yet managed to get the achievement again :(
> 
> image

Weird! It should be working (tested it on a new account as well), will take another look at this later today.

**Review by Felienne — CHANGES_REQUESTED** [review]
Tried again but I can't seem to get the achievement (Chrome or Safari on mac)

**Comment by TiBiBa** [comment]
Found it! It was broken due to the routing re-structuring. The achievement push from the front-end was made to the `/achievements` route. But due to the re-structuring the route was not found as `/achievements/achievements`. This is fixed and we also fixed a minor issue on a smaller screen where the error/warning box of the code editor would overlay on the achievement pop-up.

**Review by Felienne — APPROVED** [review]
Check:

image

**Pull request merged**
