### PR TITLE
Removed Variable view in level 1

### PR DESCRIPTION
**Pull request by fRedelaar**
**Description**
Removing the variable view in level by Marleen and Onno's request, since there are no variables yet in level 1.

**Fixes issue #2735 **

**How to test**
Go to level 1, make sure that you are not able to click on the label button. Level 2 and beyond should have the variable view button. 

image

### CODE REVIEW

**Comment by Felienne** [comment]
Good work @fRedelaar! 

I was thinking, could we hide the icon/dropdown also in case there are no variables in the program? I think we can do that in the front end entirely (since you need to populate the dropdown?) But if needed, I can easily output an extra boolean from `parse()` to tell you if there are vars in the program.

**Review by TiBiBa — CHANGES_REQUESTED** [review]
I'm still seeing the variable view on level 1, is there something I should update?
Schermafbeelding 2022-05-17 om 16 08 51

**Comment by fRedelaar** [comment]
> I'm still seeing the variable view on level 1, is there something I should update? Schermafbeelding 2022-05-17 om 16 08 51

That is strange! Could you maybe recompile TypeScript?  Or empty cash and do a hard reload? 
`
npx esbuild static/js/index.ts --bundle --sourcemap --minify --target=es2017 --global-name=hedyApp --outfile=static/js/appbundle.js`

**Comment by fRedelaar** [comment]
> 

Hi @Felienne! Nice suggestion, I will look into it :)

**Review by TiBiBa — APPROVED** [review]

**Pull request merged**
