### PR TITLE
Adding blur button after program is submitted

### PR DESCRIPTION
**Pull request by jdomil**
**Description**

Adds a blur button that hides the code in the exercise after a program has been submitted 

**Fixes _issue or discussion number_**

Fixes [https://github.com/Felienne/hedy/issues/3250](https://github.com/Felienne/hedy/issues/3250)

**How to test**

* Go to [http://localhost:8080/hedy](http://localhost:8080/hedy)
* Hit the run code button
* After the success message disappears, the blur button will be available
* Click the blur button to ensure the code is blurred out

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks for your first contribution @jdomil!!! 🥳

**Comment by Felienne** [comment]
Great, this works!!!!

image

That will make it easier for kids in my class to demo their programs!

However, it now also shows the button in the regular UI:

image

I am not sure we also want that; we originally only placed in the Developer's mode only so that the regular UI is not too overwhelming for kids. 

Would it be hard to show the blur button *only* on the submitted program page (f.e. http://0.0.0.0:8080/hedy/60796e6780de42e084a65d143f97ed3d/view)

**Comment by Felienne** [comment]
Great, this works!!!!

image

That will make it easier for kids in my class to demo their programs!

However, it now also shows the button in the regular UI:

image

I am not sure we also want that; we originally only placed in the Developer's mode only so that the regular UI is not too overwhelming for kids. 

Would it be hard to show the blur button *only* on the submitted program page (f.e. http://0.0.0.0:8080/hedy/60796e6780de42e084a65d143f97ed3d/view)

**Comment by jdomil** [comment]
Hey @Felienne ! Apologies, I think I misunderstood the issue. I didn't know there was a view for the submitted program only, I thought the desired outcome was that the blur button is showed after the student submits the program. Let me have a look at the required fix, make some changes, and create another PR. :)

**Pull request closed without merging**
