### PR TITLE
Thematic confetti #1294

### PR DESCRIPTION
**Pull request by johannadekker**
Fix for #1294 

We have added thematic confetti for certain adventures within a level. The confetti is based on emojis. The size and amount has been adjusted for increased visual appeal.
preview_fix

### CODE REVIEW

**Comment by Felienne** [comment]
Just to summarize my question from yesterday: I would prefer that these emoji live in coursedata/adventures/ so they are more easy to customize.

There is logic to grab data from the yamls and use it in the frontend already so that can be repurposed here.

**Comment by fRedelaar** [comment]
> Just to summarize my question from yesterday: I would prefer that these emoji live in coursedata/adventures/ so they are more easy to customize.
> 
> There is logic to grab data from the yamls and use it in the frontend already so that can be repurposed here.

Would you like us to work on that in this MR, or should we create a new issue?

**Comment by Felienne** [comment]
A separate issue is fine with me too, it is fun to deploy this now :)

**Comment by fRedelaar** [comment]
Cool! Issue #1414 has been made :)

**Review by Felienne — APPROVED** [review]

**Comment by Felienne** [comment]
Hmmm somehow there is a ts error now not sure how to fix this, can you have a look @johannadekker?

**Comment by fRedelaar** [comment]
Sorry for the redundant commits, closing and reopening the PR. The checks wouldn't run... so I thought I had to send an empty commit or reopen the PR to force the unit checks on Github.

**Review by Felienne — APPROVED** [review]

**Comment by Felienne** [comment]
Haha I see! You can also run the all tests on your own machine so you don't
have to rely on github. The tests are located in tests/ and the buildtools
are located in /buildtools

**Pull request merged**
