### PR TITLE
[CLEAN-UP] Replaces mail YAMLs with gettext

### LINKED ISSUE #2476: [CLEAN-UP] Move e-mail translations from .YAMLS to Babel
**Description**
Currently we store the e-mail translations in .YAML files. It would be nice to switch these to gettext as well.

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we move the mail translations from YAML files to the gettext structure, simplifying our codebase. This is mostly a clean-up task as we simply move the translations. But as we re-write some back-end structure as well some testing is needed that everything still works.

**Fixes**
This PR fixes #2476.

**How to test**
This cannot be tested locally. When the tests pass we should merge and verify that it's all working with the templates by performing the following actions in multiple languages:

- Create an account (receive a verification mail -> verify that link is working)
- Reset password
- Recover password
- Set account as teacher (only the admin can do this @Felienne) -> also receive mail

### CODE REVIEW

**Comment by Felienne** [comment]
Haha good luck @TiBiBa 

image

@Mark-Giesen Can this be merged or does it require Weblate changes?

**Comment by TiBiBa** [comment]
> Haha good luck @TiBiBa
> 
> image
> 
> @Mark-Giesen Can this be merged or does it require Weblate changes?

Haha. hopefully only headers this time! Will take a look in a minute.

**Comment by Mark-Giesen** [comment]
> Haha. hopefully only headers this time! Will take a look in a minute.

Yes this needs a weblate change. The last one for a time.

**Comment by Mark-Giesen** [comment]
> @Mark-Giesen Can this be merged or does it require Weblate changes?

Yes this needs a weblate change, the last one for a while (I think)

**Comment by TiBiBa** [comment]
I performed the same steps as the previous times to fix the merge conflicts. Simply accept the header as provided by Weblate (and main in this case). I assume that after we are done with the YAML re-structuring and clean-ups these issues will occur less often.

**Comment by Felienne** [comment]
> > @Mark-Giesen Can this be merged or does it require Weblate changes?
> 
> Yes this needs a weblate change, the last one for a while (I think)

ok! let us know when you are ready (you of course may also merge it yourself

**Review by Mark-Giesen — APPROVED** [review]

**Pull request merged**
