### PR TITLE
Add Keywords to the translate page

### PR DESCRIPTION
**Pull request by teundemast**
**Description** 
With this pull request, it will be possible to give a translation for all the keyword tokens on the translation page. Then, these translations can be downloaded in a yaml file and can be added to coursedata/keywords/. I have added a function in the file yaml_transformer.py, which can create lark files in the grammars directory for yaml files in the coursedata/keywords/ directory. There is an option to overwrite all these lark files or just add new lark files without overwriting the other ones. The approach in the function I have added in yaml_transformer.py, differs a bit from the existing transforming functions. This is because I could not get these function to work on my device (I kept getting import errors while all packages in requirements are installed). I don't know if this happened because of my device or because of some updates in modules. Anyway, I hope that the way the 'transform_yaml_to_lark' function works is also fine. 

I have updated TRANSLATING.md accordingly. 

Fixes issue #1109 

**How to test**

- Go to http://localhost:5000/translate/en/new
- Fill in the translations for the keywords
- Download keywords/new.yaml 
- Add it to the directory coursedata/keywords
- Run yaml_transformer.py (at least the function transform_yaml_to_lark)
- If all goes well, a keywords-new.lark file should be added to the directory grammars

### CODE REVIEW

**Review by Felienne — CHANGES_REQUESTED** [review]
Great PR with clear changes, and awesome that you also updated the MD files.

Just one (small) issue, if you do not translate all keywords, you get a weird yaml file:

image

Can we default to English if a keyword was not translated? Because your yaml transformer does not properly consume this version (you may also change the transformer)

**Comment by teundemast** [comment]
Thanks for your feedback! I will look into that! For now, I will convert this PR to a draft and open it again when PR #1293 is accepted (this will prevent conflicts) and I have fixed that issue.

**Comment by Felienne** [comment]
> Thanks for your feedback! I will look into that! For now, I will convert this PR to a draft and open it again when PR #1293 is accepted (this will prevent conflicts) and I have fixed that issue.

ok!

**Comment by teundemast** [comment]
Hi @Felienne, I have changed the transformer so it will retrieve the English keyword when the translation of a keyword is not yet filled in. Due to recent commits in the main branch, changes I made with PR #1293 were erased. I don't think that was the intention, so I have put these changes in this PR.

**Comment by Felienne** [comment]
Closing because of merge issues, see #1309

**Pull request closed without merging**
