### PR TITLE
[Cleanup] Removed language dependency on url argument

### LINKED ISSUE #1496: [UI idea] Store current language in session and prevent url argument dependency
**Idea incl level**
Currently we depend on the `?lang=` addition to the url to retrieve the user selected language. Because of this we use a parsing function to localize each url to make sure the user gets the next page in the same language when switching pages. This is cumbersome, especially with the goal of #1467 and #1478 to enable logged in user to set a fixed language in their profile settings. I propose that we alter this structure and store the current language in the user sessions, cleaning up the url and making the implementation of the other mentioned issues easier.

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
Currently we depend on an `lang` argument added to the url to tell us the language we have to render the current page in. This is cumbersome as we have to pre-process each url to make sure the user keeps the same language when switching pages. In this PR we implement the chosen language in a session variable, living on the server. Removing the need from sending the argument with the url and in the same process cleaning this url as well. This PR will also make it significant easier to implement #1478.

**Fix for**
This PR fixes #1496.

**How to test**
Navigate through different pages and notice that the `lang` attribute is no longer passed in the url. Try different languages to verify the correct updating of the stored session variable.

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] Links to an existing issue or discussion (if not, create an issue first)
- [ ] Describes changes clear in the format above (present tense, no subject)
- [ ] Has a "how to test" section
- [ ] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by Felienne** [comment]
It seems that the lang is still used if people click the advance button, is that as expected?

image

**Comment by Felienne** [comment]
> It seems that the lang is still used if people click the advance button, is that as expected?
> 
> image

I think this is located in incl-editor-and-output.html which indeed this PR does not seem to update?

**Comment by TiBiBa** [comment]
> > It seems that the lang is still used if people click the advance button, is that as expected?
> > image
> 
> I think this is located in incl-editor-and-output.html which indeed this PR does not seem to update?

Forgot that one, will fix with a new commit right away!

**Comment by Felienne** [comment]
Ah looks better now the langs are clickable again!

**Review by Felienne — APPROVED** [review]

**Pull request merged**
