### PR TITLE
Fixes Issue1996: if and elses might be separated by newline

### PR DESCRIPTION
**Pull request by racertop**
This PR is a partial fix for issue #1996. This way we can accept this type of code in levels 4, 5 and 6

**Description**

I changed the `ifelse` rule in the level 4 grammar so it's similar to the `ifs` rule in  the same grammar.

**Fix for**
This fix is so we can accept this type of code.
```
if condition
command
else
command
```
Notice that there aren't any leading spaces in this code, just separated by newlines.

**Why a draft**
I'm having some issues making it work. It works fine enough when I'm debugging and the parser is not cached, but once it's cached it says invalid in some cases. The issue lies in this line of code:
When it falls in that if, something happens that my grammar is not valid anymore, as opposed to when is build from scratch. 
image

 When there's a mathematical operation, it doesn't work either, which is something that also happens with the current ifs rule that accepts newlines.
```
people is 1, 2, 3, 3
dishwasher is people at random
test is 1
if dishwasher is test
print 'too bad I have to do the dishes'
else
print 'luckily no dishes because' dishwasher + 1 'is already washing up'
```
All the help you can provide will be much appreciated.
**How to test**

You can use this code in levels 4, 5 or 6. Or anything that resembles it:
```
people is mom, dad, Emma, Sophie
dishwasher is people at random
if dishwasher is Sophie
print 'too bad I have to do the dishes'
else
print 'luckily no dishes because' dishwasher 'is already washing up'

```

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] Links to an existing issue or discussion (if not, create an issue first)
- [ ] Describes changes clear in the format above (present tense, no subject)
- [ ] Has a "how to test" section
- [ ] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @racertop! 

I think I managed to fix your issue by disallowing else in the invalid clause. That way it will never match and we always match with the real actual else. In a near future, we might be able to parse ambiguously so this type if hacking is no longer needed :) 

Hope this helps!

**Comment by racertop** [comment]
Hi @Felienne, thank you so much for your help! I think it's ready now, I edited the `invalid` rule a bit further disallowing the if else too, because the same problem happened with this type of programs:
```
if condition
statement
```

**Comment by Felienne** [comment]
Awesome work @racertop!! This is really going to help kids a lot. Let me know when this is ready to be merged.

**Comment by racertop** [comment]
Thank you, @Felienne! I think it's ready for merge right now, I added a few test too so you can check them out!

**Review by Felienne — APPROVED** [review]

**Comment by Felienne** [comment]
Thanks again @racertop for your hard work on this!

**Pull request merged**
