### PR TITLE
Fix: Class name can't be empty or duplicate

### LINKED ISSUE #1152: [BUG] Class name can be empty
**Describe the bug**
When re-naming an already existing class we are able to leave the input field empty: resulting in a class without a name. This is undesirable behavior and should be checked when the "apply" button is pressed. More importantly: when the name is empty we are unable to enter the class because there is no string to click! Closely related to this it might be nice to enforce unique name choosing for classes. Making sure that all classes of a teacher have unique names

**Add a screenshot (optional)**
We are unable to join the class in the screenshot below because the name is empty!
Schermafbeelding 2021-11-03 om 12 06 10

**Expected behavior**
Return an error message when an empty string or duplicate class name is entered.

### LINKED ISSUE #1278: [BUG] Class names can be duplicate
**Describe the bug**
Currently, we are able to create multiple classes with an identical name. I think this is undesirable and should be prevented. Might be best to tackle this issue at the same time as #1152.

**Paste the Hedy code & level**
It is super helpful if we can copy-paste the Hedy code to test, so please paste the code here, and don't forget to tell us what level you were in.

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

**Expected behavior**

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

### PR DESCRIPTION
**Pull request by TiBiBa**
Provide a general summary of your changes in the Title of the PR

**Description**
In this PR we add two additional checks to the changing of a class name to improve user experience. First, we verify that the name can't be empty. This was possible, resulting in a class we were not able to click as it didn't have a name. Next we verify if the chosen class name isn't already existing for this teacher. Duplicate class names by the same teacher are undesirable and shouldn't be allowed.

**Fix for**
This PR fixed #1152 and fixed #1278 

**How to test**
Sign in with a teacher account and on the teachers page select one of your classes. Press the button to rename the class and leave it either empty of type the name of one of your other classes. In the first scenario a modal with the `class_name_empty` message should be returned. In the second scenario a modal with the `class_name_duplicate` should appear. Notice that the second message will also appear if the chosen name is identical to the previous name.

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] Links to an existing issue or discussion (if not, create an issue first)
- [ ] Describes changes clear in the format above (present tense, no subject)
- [ ] Has a "how to test" section
- [ ] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @TiBiBa 

I just tested this locally (macos, chrome) and it seems to still allow me to create duplicate and empty classes. 

Felienne

**Comment by TiBiBa** [comment]
> Hi @TiBiBa
> 
> I just tested this locally (macos, chrome) and it seems to still allow me to create duplicate and empty classes.

I think the fix is only implemented for `rename_class` (my bad). Will alter it so the restrictions will also work when creating a new class.

**Comment by TiBiBa** [comment]
Fixed!

**Comment by TiBiBa** [comment]
Fixed!

**Pull request merged**
