### PR TITLE
Fixes string printing for lvl 13

### PR DESCRIPTION
**Pull request by tuxo**
**Description**

This change fixes a bug for string printing in lvl 13. Even when you tried to print a quoted string, it would still be treated as a variable (if there was a variable with the same name as the string).

**Fix for**

#1126 

**How to test**

Go to lvl 13 and run the following code:
```
fruit is ['banaan', 'appel', 'kers']
eerstefruit is fruit[1]
print('eerstefruit') # should print eersterfruit
```
and then run the next one:
```
fruit is ['banaan', 'appel', 'kers']
eerstefruit is fruit[1]
print(eerstefruit) # should print banaan
```

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [x] Links to an existing issue or discussion (if not, create an issue first)
- [x] Describes changes clear in the format above (present tense, no subject)
- [x] Has a "how to test" section
- [x] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by Felienne** [comment]
Works!

image

Thanks again @racertop!

**Comment by Felienne** [comment]
Closes #1126

**Review by Felienne — APPROVED** [review]

**Comment by racertop** [comment]
> Works!
> 
> image
> 
> Thanks again @racertop!

Hahaha, I didn't do this one 😅 it's all @tuxo. Cool contribution by the way!

**Comment by Felienne** [comment]
Haha oops, mixed up two PR's.

Thanks @tuxo!!!!!

**Pull request merged**
