### PR TITLE
Separates keyword rules and adds some other improvements

### LINKED ISSUE #724: syntax highlighting after `echo`
When you use an `echo` command without any text e.g.:
```
ask yes or no?
echo 
print okay
```

The syntax highlighting does not work for the command after `echo`. So in the example above, `print` is not highlighted.

### LINKED ISSUE #2167: [BUG] Syntax highlighting sometimes breaks the front-end code
**Describe the bug**
Currently the syntax highlighting sometimes seems to break due to a regular expression error. The bigger issue is that due to this error occurring all TypeScript code stops working. Resulting in a non-responding website where we can't switch levels, logout or have any other dynamic interaction. The problem seems to occur from level 3 and onwards and on specific programs (for example on the explore page). The following front-end error message seem to point to the problem:

Schermafbeelding 2022-03-04 om 21 00 16

**Expected behavior**
Syntax highlighting should work fine on alle levels. When for some reason it doesn't work the error should be caught preventing the crashing of our complete front-end interaction.

### LINKED ISSUE #2240: unwanted syntax highlighting for qoutation marks in level 2
If you use multiple quotation marks in level 2 it will highlight the syntax between them. This is confusing as quotation marks are introduced in level 4.

This code:
`print hij houdt van auto's en dino's`

is highlighted like this:
image

### LINKED ISSUE #2254: [BUG] Syntax highlighting not working for Dutch keyword "add"
**Describe the bug**
In level 3 it becomes possible to add and remove listitems. The keywords in English are "add" and "remove". They are highlighted as keywords. In Dutch, the keywords are "voeg ... toe aan" and "verwijder ... uit".  The Dutch keyword "remove" seems to work perfectly. The "add" keyword does not however. The words "Voeg" and " toe aan" should be highlighted as well. 

**Paste the Hedy code & level**
Level 3, use NL keywords
```
dieren is hond, kat, koe
voeg appel toe aan dieren
verwijder hond uit dieren
print dieren op willekeurig
```

**Add a screenshot (optional)**
image
image

**What machine and browser you were using**
- Using Windows
- Using Chrome

### PR DESCRIPTION
**Pull request by thjazi39**
repair of the PR : #2137 

I found a way without the lookbehind, and without other modules.
It should work, even on Safari

fix #724 
fix #2167
fix #2240 
fix #2254

### CODE REVIEW

**Comment by Felienne** [comment]
Wow, well done @thjazi39!!!

I will test this extensively now, also on Safari!

**Comment by Felienne** [comment]
Documenting my testing work here:

Issue #724 in Chome ✅ 

image

in Safari: ✅ 

image

**Comment by Felienne** [comment]
Fixes #2240 in Chrome ✅ 

image (tested for levels 1 to 3)

And in Safari ✅ 

image

**Comment by thjazi39** [comment]
The tests are done in French, English, Dutch, and Spanish versions
<table>
      <tr>
        <th>Bug</th>
        <th> Code </th>
        <th>Firefox on Linux</th>
        <th>Vivaldi on Linux</th>
        <th>Chromium on Linux</th>
        <th>Safari on VirtualBox on Linux</th>
      </tr>
      <tr>
        <th>#724</th>
<td><pre>print Welcome at Hedy's
ask What would you like to eat?
echo So you want 
ask what would you like to drink?
echo So you want</pre>

<pre>ask yes or no ?
echo 
print okay</pre>
</td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
      </tr>
      <tr>
        <th>#2240</th>
<td> <pre>print hij houdt van auto's en dino's
print hij houdt van "autos en dino"s</pre></td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
      </tr>
      <tr>
        <th>#2254</th>
<td> <pre>dieren is hond, kat, koe
voeg appel toe aan dieren
verwijder hond uit dieren
print dieren op willekeurig</pre></td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
<td> [x] French <br/> [x] English <br/> [x] Dutch <br/> [x] Spanish</td>
      </tr>
    </table>

**Comment by Felienne** [comment]
Confirming #2254 works, on Chrome ✅  

image

Safari ✅ 

image

**Comment by Felienne** [comment]
> The tests are done in French, English, Dutch, and Spanish versions
> 
> Bug	Code	Firefox on Linux	Vivaldi on Linux	Chromium on Linux	Safari on VirtualBox on Linux
> #724	
> print Welcome at Hedy's
> ask What would you like to eat?
> echo So you want 
> ask what would you like to drink?
> echo So you want
> ask yes or no ?
> echo 
> print okay
> [x] French
> [x] English
> [x] Dutch
> [x] Spanish	[x] French
> [x] English
> [x] Dutch
> [x] Spanish	[x] French
> [x] English
> [x] Dutch
> [x] Spanish	[x] French
> [x] English
> [x] Dutch
> [x] Spanish
> #2240	
> print hij houdt van auto's en dino's
> print hij houdt van "autos en dino"s
> [x] French
> [x] English
> [x] Dutch
> [x] Spanish	[x] French
> [x] English
> [x] Dutch
> [x] Spanish	[x] French
> [x] English
> [x] Dutch
> [x] Spanish	[x] French
> [x] English
> [x] Dutch
> [x] Spanish
> #2254	
> dieren is hond, kat, koe
> voeg appel toe aan dieren
> verwijder hond uit dieren
> print dieren op willekeurig
> [x] French
> [x] English
> [x] Dutch
> [x] Spanish	[x] French
> [x] English
> [x] Dutch
> [x] Spanish	[x] French
> [x] English
> [x] Dutch
> [x] Spanish	[x] French
> [x] English
> [x] Dutch
> [x] Spanish

With tested you mean manually tested right?

**Review by Felienne — APPROVED** [review]
Wow, super well-done @thjazi39!!!

**Comment by Felienne** [comment]
@thjazi39 This was merged and thus now deployed on [alpha](https://hedy-alpha.herokuapp.com/, do test it a bit there to see if all is in order before we deploy to prod

**Pull request merged**
