### PR TITLE
Attention adding Hungarian

### PR DESCRIPTION
**Pull request by moorlag**
Contributions for the language goes to Ágota, thanks for the effort and energy :-) 

There are two failures I can't resolve:

- File "/Users/ramonmoorlag/Documents/GitHub/hedy/app.py", line 53, in <module>
HEDY_COURSE[lang] = courses.Course('hedy', lang, LEVEL_DEFAULTS[lang])

- File "/Users/ramonmoorlag/Documents/GitHub/hedy/courses.py", line 34, in __init__
raise RuntimeError(f'File should have top-level "course" field: coursedata/course/{course_name}/{language}.yaml')

Translated files

- [Levels](https://drive.google.com/file/d/1qMhdUMYCywg0S7SQMXiIzU_Mb73_DxB9/view?usp=sharing)
- [Course Data](https://drive.google.com/file/d/18RtO8zqLwYN7xikDsRoX7lHhMpH-k1u2/view?usp=sharing)
- [Interface](https://drive.google.com/file/d/11VYOetrBUbuvHt5qVsj-V93iEodaZ02-/view?usp=sharing)

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks @ramon! I can look into the issues for you. We are shifting some stuff around in the language files anyway so I will merge these when all is stable again.

**Comment by Felienne** [comment]
Ha Ramon!

Er zijn een paar issues met je pr waardoor we m niet makkelijk kunnen mergen. Ten eerst loop je wat achter bij de master, zou jij eerst lokaal `git pull` kunnen doen? Ook commit je wat changes mee die niet echt horen bij de Hongaarse vertaling, iets in app.py (maar dat komt denk ik door jouw ouder versie) en ook wat andere changes aan de 404 pagina en aan de nl tekst. Kan jij die changes (als je die ook wilt voorstellen) in een losse pr zetten?

**Comment by fpereiro** [comment]
Hi @moorlag ! Thanks for the contribution! From what I see, there are many changes to `app.py`, many of them reversions of newer code - ideally there should be only one change to this file in the case of a new translation, which is the adding of an extra field in the object `ALL_LANGUAGES`. As Felienne said, the 404 page is a great idea, but best to have it in a different PR.

If you need help with the PR let me know.

Cheers!

**Comment by moorlag** [comment]
hi @Felienne and @fpereiro, 

I've based that on the [contribution](https://github.com/Felienne/hedy/blob/master/CONTRIBUTING.md) in this repo.
Shall I ignore the app.py-part?

**Comment by fpereiro** [comment]
Hi Ramon! It's better to ignore it now, because the branch's version of
app.py has many changes that I believe are reversions to an older version
of app.py. I can modify app.py after we merge :).

чт, 29 апр. 2021 г. в 13:45, Ramon Moorlag ***@***.***>:

**Comment by Felienne** [comment]
Closed by #344 Thanks for your efforts!!

Hungarian is now available in our test environment (hedy-alpha.herokuapp.com) and we will soon release it to the main site too.

**Pull request closed without merging**
