### PR TITLE
Program Repair: Changed the Bulb to Hedy bulb

### PR DESCRIPTION
**Pull request by fRedelaar**
**Description**

For issue #1200 @johannadekker created SVG files of a bulb in Hedy style. This PR implements the SVG files. Whenever it is being hovered, the Hedy Bulb's hair light up.

It will look very similar as the video below, except that it is polished a bit and the hair has a yellowish glow. 

https://user-images.githubusercontent.com/33595265/141980337-78cc1f91-e2b0-4fe6-a5a3-68b0d5a7ba23.mov

### CODE REVIEW

**Comment by Felienne** [comment]
Looks supernice, thanks!!

The only thing is that the "hitbox" around the bulb seems quite large left to right (macos, Chrome):

https://user-images.githubusercontent.com/1003685/143062602-86747950-283f-4d78-90c0-6a92a291d3c3.mov

Can we make that a bit smaller?

**Comment by fRedelaar** [comment]
@Felienne You are absolutely right! @johannadekker will adjust the SVG a bit, and then I'll commit the adjusted files :)

**Comment by Felienne** [comment]
Hi all! I am going to deploy this anyway because we have a workshop today and it would be so nice to have the new image in there. Can you open an issue for the smaller svg?

**Review by Felienne — APPROVED** [review]

**Comment by fRedelaar** [comment]
> Hi all! I am going to deploy this anyway because we have a workshop today and it would be so nice to have the new image in there. Can you open an issue for the smaller svg?

Sounds very exciting, good luck with the workshop :)! I've made a new issue #1378 here.

**Pull request merged**
