### PR TITLE
greek support

### PR DESCRIPTION
**Pull request by dimnikolos**
Are you interested in Greek language support? I am willing to translate the project. I already translated levels.json and texts.json but they still need work. In my machine I had to add encoding = "utf8" for the translations to work but maybe that's a configuration problem.

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @dimnikolos!

We'd love Greek support! Let me know when you are ready with all changes you intend to make. We happen to have a Greek person in our team too, so we can do some checks if needed.

**Comment by Felienne** [comment]
Hi! I am not sure why you closed the PR? Let me know when you are ready to merge.

**Comment by dimnikolos** [comment]
Now I am ok. Please have your team member check it. Let me know when there is more content in English.

**Comment by dimnikolos** [comment]
I will create another pr with the new yaml structure.

**Comment by Felienne** [comment]
Ow that would be really lovely! Sorry for overhauling everything while you were working on this!

**Pull request closed without merging**
