### PR TITLE
[FEATURE] Create interactive tutorial for new users

### LINKED ISSUE #2679: [UI idea] Implement walk-through tutorial for first-time users
**Idea incl level**
It would be nice to have an interactive walk-through tutorial when a users logs in for the first time. Showing and explaining the different features of the Hedy code page. As we add more and more features the UI can feel crowded and hard to understand. With a nice explanatory walk-through we can help new users better understand the website.

As this is a very (very) big project we should try to divide this into multiple parts. Maybe first focus on users, then focus on teachers. For users we can aim on the code page whereas for teachers on the for-teachers page.

### LINKED ISSUE #2703: [FEATURE] Create interactive tutorial for teachers
**Description**
In #2680 we create an interactive tutorial for new users to explain the Hedy code interface and related functions. It would be nice if we create a similar tutorial for teachers as the teacher UI can be difficult to understand with all functionaliteit without a clear introduction. We can re-use a lot of the code already written in #2680 so it might be best to start this issue after that one is merged.

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we add an exciting new functionality: An interactive tutorial! The Hedy interface has become a bit crowded with new features and functionalities, making it harder for new users to understand our interface. We aim to tackle this issue by creating an interactive tutorial that is automatically shown to new users. Making all UI elements visible one by one and explaining their functionality. We also add two achievements for both the student and teacher tutorial.

**Fixes**
This PR fixes #2679 and fixes #2703.

**How to test**
Make sure you are logged in and then navigate to `/tutorial` and walkthrough the different steps. Another option is to create a new account, login and get re-directed to the landing page. This page is updated as well and select the "start tutorial" option. To view this page you can also simply login and navigate to `/landing-page`. Make sure you are a non-teacher account in this case! Otherwise the landing-page will only show the teacher tutorial option.

For the teacher tutorial follow the same steps, make sure you are logged in and navigate to the landing page. Another option is to directly navigate to `/teacher-tutorial`. Verify that all steps are working, also in combination with the newly added achievements.

### CODE REVIEW

**Comment by TiBiBa** [comment]
To-do on this PR:

- Split the tutorial into two parts:
    - The current "code page" tutorial
    - An additional profile settings / achievements / public profile tutorial
- Enable users to re-start the tutorial

**Comment by TiBiBa** [comment]
Few enhancements that would be nice to implement:

- Change popup direction by (x, y) coordinates
- Reverse empty layout view -> show completely view and highlight the relevant section

**Comment by TiBiBa** [comment]
Update: Added an extra step to explain the next/previous level buttons

**Comment by boryanagoncharenko** [comment]
It looks great!

The only thing that could be improved is the interplay between tutorial steps and achievement pop-ups. If I create a new account and I click the "Run program" button (as the tutorial recommends), the achievement pop-up will appear above the tutorial dialog:
Screenshot 2022-05-11 at 10 50 56

However, in other cases it seems that the achievement appears directly on the tutorial dialog.
Screenshot 2022-05-11 at 10 49 24

Screenshot 2022-05-11 at 10 51 02

Note that I cannot close the achievement pop-up, I have to patiently wait for it to disappear. Also, the achievement does not give me an indication that it is there temporarily. Anyway, for me this falls under the category of improvements.

**Review by boryanagoncharenko — APPROVED** [review]

**Comment by TiBiBa** [comment]
> It looks great!
> 
> The only thing that could be improved is the interplay between tutorial steps and achievement pop-ups. If I create a new account and I click the "Run program" button (as the tutorial recommends), the achievement pop-up will appear above the tutorial dialog: Screenshot 2022-05-11 at 10 50 56
> 
> However, in other cases it seems that the achievement appears directly on the tutorial dialog. Screenshot 2022-05-11 at 10 49 24
> 
> Screenshot 2022-05-11 at 10 51 02
> 
> Note that I cannot close the achievement pop-up, I have to patiently wait for it to disappear. Also, the achievement does not give me an indication that it is there temporarily. Anyway, for me this falls under the category of improvements.

Agree! I think it would be nice to give the achievements pop-up an overall restyling as I noticed this as well when giving a workshop. Users would prefer to be able to close the pop-up or at least know when it will be closed. Will open a separate issue for this and take a look at a possible solution! Other than that I think this tutorial PR can be merged?

**Pull request merged**
