### PR TITLE
[UI IMPROVEMENT] Re-structured class customizations

### LINKED ISSUE #1606: [UI idea] Re-structure class customizations
**Idea incl level**
Currently teachers are able to customize specific levels in their classroom. However, there is no support for setting specific values or settings for the whole class. It would be nice if we implement some "general settings" option on the customizations in which teacher are able to set some global preferences, such as:

- Fixed language
- Hide non-translated adventures
- Enable / disable submitting of programs

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we improve the implementation of the class customizations. Currently we store the customizations as a [class_id, level] pair. This is quite cumbersome because we also keep track of the restriction of previous or next Hedy levels. Resulting in the situation that we have to update three db rows at every update. We also have (a lot!) of duplicate storing of data due to storing the available adventure names in each row. We improve this by implementing the following structure:

```
"class_customizations" {
"class_id": 1234,
"levels": [2,3,4],
"adventures: [
    "Story": [1, 2, 3, 4],
    "Parrot": [1, 2, 3]
]}
```

Using only one db row to store the chosen levels and the chosen levels per adventures. After merging #1812, we will have to change the structure slightly to support personal adventures as well. Overall the code is significantly simplified, on the front-end and well as the back-end. Making it easier to understand and alter the functionality of customizations.

**Fix for**
This PR fixes #1606.

**How to test**
This is mostly a clean-up task so for end-user there should be no visible change. For teachers: log in, navigate to one of your classes and verify that the UI of the customizations is changed. Try different level, adventure combinations and (when being a student of your own class) verify that these are correctly customized on the coding page.

**Important**
Due to the new structure we have to delete all old customizations from the database. This might influence some teachers and classes currently actively working with Hedy. We should notify them to manually copy there customizations to the new format.

### CODE REVIEW

**Comment by TiBiBa** [comment]
Supporting a clear overview of adventure selection in a grid:

Schermafbeelding 2022-01-31 om 17 52 16

**Comment by TiBiBa** [comment]
Dynamic adventure selecting:

Schermafbeelding 2022-02-01 om 10 18 01

**Comment by TiBiBa** [comment]
To-do:

- Set checkboxes checked for each value that already in db
- Improve front-end UI
- Implementation additional customizations
- **What to do with current customizations? delete / migrate**

**Comment by TiBiBa** [comment]
Hi @MarleenGilsing, @OnnoEbbens! We are currently working on re-structuring the class customizations. The old implementation was a bit cumbersome and made it difficult to change things. I would love to have your input on things you would like to be able to customize for your class! The current functionality is:

- Restrict levels
- Restrict adventures
- Show personal adventures

Possible functionality I was thinking about:

- Forced language (set all users to dutch for example)
- "Exam mode" (force set the users to programmer's mode)
- Enable/disable explor
- Enable/disable public profile

With our new implementation it is very easy to edit and adjust front-end changes for the user so if you have any ideas let me know!

**Comment by MarleenGilsing** [comment]
Again some great changes! 😍
I love how this gives the teachers (and me haha) a great overview of all the adventures and the levels in which they are available. This will really help them with making a lesson plan. 
I really like how the system works. It's clear with the explaining text. 

Typo 'you can **choice** what your students can see'. 

This sentence needs to be changed: 'This way it is easier for the students (and the teacher!) to select what can be worked on and what skills can be learned.' Maybe something like: 'This way it's easy for you to determine which level and adventures your students will be working on.'
 
In Dutch I would change 'checkbox' to slectievakje or vinkjes. 

I think the reset button needs an 'are you sure?' message. 

I love how you can turn an adventure on in all levels by clicking the name of the adventure. It would be great if it also worked for turning it off by clicking it again. 

I haven't found out how to add my own adventure to the table. But I must say that I forgot how to add my own adventure at all, but I guess that's because it's on a different branch/PR so that's just my bad. 

I have some ideas which could possibly make it easier to understand without having to read the instructions. But they are not nessecary changes, because it works fine now too, so do what you want with it haha: 
- Maybe instead of having the levels in a separate table, you could make the levelnumbers in the main table clickable and turn blue if they are 'on' or put a lock picto near the number and have the lock opened or closed or something like that. This way you only need one table.
- Maybe instead of having a 'reset selected adventures button' add a line above the story adventure called 'all adventures' that could turn all adventures in that level on at once? (and then start with them all off).

**Comment by TiBiBa** [comment]
> Again some great changes! 😍 I love how this gives the teachers (and me haha) a great overview of all the adventures and the levels in which they are available. This will really help them with making a lesson plan. I really like how the system works. It's clear with the explaining text.
> 
> Typo 'you can **choice** what your students can see'.
> 
> This sentence needs to be changed: 'This way it is easier for the students (and the teacher!) to select what can be worked on and what skills can be learned.' Maybe something like: 'This way it's easy for you to determine which level and adventures your students will be working on.'
> 
> In Dutch I would change 'checkbox' to slectievakje or vinkjes.
> 
> I think the reset button needs an 'are you sure?' message.
> 
> I love how you can turn an adventure on in all levels by clicking the name of the adventure. It would be great if it also worked for turning it off by clicking it again.
> 
> I haven't found out how to add my own adventure to the table. But I must say that I forgot how to add my own adventure at all, but I guess that's because it's on a different branch/PR so that's just my bad.
> 
> I have some ideas which could possibly make it easier to understand without having to read the instructions. But they are not nessecary changes, because it works fine now too, so do what you want with it haha:
> 
> * Maybe instead of having the levels in a separate table, you could make the levelnumbers in the main table clickable and turn blue if they are 'on' or put a lock picto near the number and have the lock opened or closed or something like that. This way you only need one table.
> * Maybe instead of having a 'reset selected adventures button' add a line above the story adventure called 'all adventures' that could turn all adventures in that level on at once? (and then start with them all off).

Thanks for all your feedback! Will set this on draft until I have time to fix it. Will let you know when it's finished!

**Comment by TiBiBa** [comment]
Hi @MarleenGilsing ! I implemented two new features as requested:

- You can (de)select adventures by pressing the name again
- You can select levels by pressing the corresponding button, simplifying the UI

Schermafbeelding 2022-02-03 om 15 26 52

**Comment by TiBiBa** [comment]
@MarleenGilsing I fixed the last issues, would be great if you could check them out! @Felienne I think this is a nice PR to merge first as it is mostly a clean-up task. Afterwards I will solve the merging errors with #1812 so that can me merged as well. We do have to notify teachers of active classes that due to the re-structuring their old customizations will be lost...

**Comment by MarleenGilsing** [comment]
Great! It looks much simpler and works nice :) 
Atm the (de)selecting the adventure by clicking it seems to be glitching a bit for me. It works sometimes, and sometimes not, so that's probably just me.

**Comment by TiBiBa** [comment]
> Great! It looks much simpler and works nice :)
> Atm the (de)selecting the adventure by clicking it seems to be glitching a bit for me. It works sometimes, and sometimes not, so that's probably just me.

Yes I think that's because we look at the first visible checkbox to decide if we either select or (de)select everything. We can change this to always toggle independent of the user's (de)selecting in between. What do you think would work better?

**Comment by TiBiBa** [comment]
> Great! It looks much simpler and works nice :)
> Atm the (de)selecting the adventure by clicking it seems to be glitching a bit for me. It works sometimes, and sometimes not, so that's probably just me.

Whoops! I just noticed I made a mistake, we only look at the very first checkbox (independent of adventure). Good catch! Will fix it right away!

**Comment by boryanagoncharenko** [comment]
Why do we have to clear the existing customisation data? The existing data could be transformed to the new structure + the DB holds only 27 records. In this way we won't have to ask teachers to import anything and overall this would be better user experience.

We could create a new table (e.g. hedy-*-class-customizations), add to it the existing data transformed to the new structure, and point Hedy to use the new table? In this way we would be able to rollback easily (if needed) without losing any production data.

**Review by Felienne — APPROVED** [review]

**Comment by Felienne** [comment]
* Fixes #1606

**Pull request merged**
