### PR TITLE
[UI IMPROVEMENT] Always shows tabs, also when in developer's mode

### LINKED ISSUE #2546: [UI idea] Improve programmers mode to still enable adventure switching
**Idea incl level**
Currently when on programmer's mode we are unable to switch adventure tabs. Especially when we are using the forced developer's mode setting in the class customizations this can be annoying.

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we fix that the adventure tabs are always shown, also when in developers mode. This way users are still able to switch adventures, store programs within specific adventures and/or make the quiz. This is currently not possible and can be cumbersome when the forced developers mode is set in class customizations.

**Fixes**
This PR fixes #2546.

**How to test**
Verify that the tabs are still shown when entering developer's mode. Also verify that the switching is still working and that the developer's mode is automatically turned off when entering the quiz tab.
If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Review by Mark-Giesen — CHANGES_REQUESTED** [review]
Syntax highlighting is gone in the code window. 
How do I see if developer mode is disabled when clicking End Quiz tab? There is no example code there to see. Moving back to an adventure shows everything still in Programmers mode (like I think it should).

**Comment by Mark-Giesen** [comment]
>How do I see if developer mode is disabled when clicking End Quiz tab? There is no example code there to see.

I do see the text "End" and button Go to Quiz, I suspect this is because programmer mode is of on this tab.

**Comment by TiBiBa** [comment]
> Syntax highlighting is gone in the code window.
> How do I see if developer mode is disabled when clicking End Quiz tab? There is no example code there to see. Moving back to an adventure shows everything still in Programmers mode (like I think it should).

My bad. It is disabled if the adventure window is shown (with the quiz in it). So more clearly: when the quiz works it works.

**Comment by TiBiBa** [comment]
There seems to be some weird issues with Typescript that broke the syntax highlighting:
Schermafbeelding 2022-04-29 om 15 22 28

**Comment by TiBiBa** [comment]
I think this should work if you compile the Typescript again. @Mark-Giesen can you take a look?

**Review by Felienne — APPROVED** [review]
Works!

image

**Pull request merged**
