### PR TITLE
[FEATURE] Adds language filtering on explore page

### LINKED ISSUE #2813: [UI idea] Allow filtering on UI language in /explore
**Idea incl level**
Since https://github.com/Felienne/hedy/pull/2808 all programs are shown in the local keywords, awesome! But I think it would be great if we can also filter on the UI language of the creator, cause a program with a lot of Spanish text is still not so very useful to me. Do we have that information? If so, can we add it as a filtering option?

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
We already support level and adventure filtering on the explore page but in this PR add the option to filter on language. Only returning the programs that are stored with a user with a profile language set to the selected language.

**Fixes**
This PR fixes #2813.

**How to test**
Make sure you are logged in, navigate to the `/explore` page and verify that language filtering is working.

### CODE REVIEW

**Review by Felienne — CHANGES_REQUESTED** [review]
ok, I know this is minuscule but language has a lowercase letter but Level and Adventure have an uppercase:

image

I wanted to fix it myself but I could not easily find the location, sorry!

**Comment by Felienne** [comment]
Also, if I am being very picky anyway, can we make the order: Adventure, Level and then Language, since the default name is also Adventure and then Level:

image

**Comment by TiBiBa** [comment]
> Also, if I am being very picky anyway, can we make the order: Adventure, Level and then Language, since the default name is also Adventure and then Level:
> 
> image

Fixed!

**Comment by Felienne** [comment]
> This is due to either Babel not being compiled or having your profile set to a non-dutch/English language. The placeholder key is "language" whereas the dutch and English translations are "Taal" and "Language".

Ah this issue again, my bad, sorry! But would it be possible to somehow label those placeholder clearly, so I know I al looking at one (I can imagine other projects would like such a feature too)?

**Comment by Felienne** [comment]
> > This is due to either Babel not being compiled or having your profile set to a non-dutch/English language. The placeholder key is "language" whereas the dutch and English translations are "Taal" and "Language".
> 
> Ah this issue again, my bad, sorry! But would it be possible to somehow label those placeholder clearly, so I know I al looking at one (I can imagine other projects would like such a feature too)?

If not, maybe we can have our own convention, like starting them with a few underscores or something?

**Review by Felienne — APPROVED** [review]

**Pull request merged**
