### PR TITLE
[FEATURE] Debugging step-per-step (combining step-per-step, breakpoints and variable view)

### PR DESCRIPTION
**Pull request by fRedelaar**
**Description**
In discussion [#2483](https://github.com/Felienne/hedy/discussions/2483). I've shown a design there for a step-by-step program executer in Hedy. This can be used to debug Hedy programs. In this PR,  this design has been brought to life.  A new button will appear. Next to the original "run it" button, there also is a new `🐞 debug` button. When this button is clicked, the Hedy program will be executed line-per-line. The user can go to the next line, using the  `⏩ button`. It can stop the debugging session using the stop button 🛑, and the user can 🔁restart the program. 

After all lines in a Hedy program have been executed line-per-line, the debugging state automatically ends. The debugger can also work together with the earlier created variable view from PR #2241. This PR also uses code from PR #2478, to set breakpoints. The variable view and the step-by-step debugger are under a feature flag.

### Screenshot line-per-line main functionality
In the screenshots I've added a yellow highlighter on my cursor. Whenever I click, the highlighter becomes red.

https://user-images.githubusercontent.com/33595265/162741657-a68f2e22-6cd6-4253-afaa-e5e4588fb370.mov

**Extra Screenshot: Using a sleepy breakpoint while debugging**

https://user-images.githubusercontent.com/33595265/162741662-831b06e4-560b-4edc-81aa-af108b41c656.mov

**Extra Screenshot: Reset and stop button while debugging**

https://user-images.githubusercontent.com/33595265/162741673-6fee6e8e-ad4f-4c4f-b0cd-8e36fed69119.mov

**How to test**
Turn the feature flags on at `app.ts`. You can do this by searching for variables `step_debugger` and `variable_view`, and changing the false statements into true. Recompile Typescript, and go to any level. Click on the 🐞 debug button. Try to execute a program line per line using the ⏩ button. Try to stop 🛑, and 🔁restart the program. 

**Limitations**
The step-by-step debugger will execute the programs per line. This works mostly fine with most keywords such as `ask`, `print`, `add to`, `remove from`, `at random`, `sleep` and all turtle commands. But it produces "weird" outcomes when using `repeat`, or even weirder when using `nested repeats`.

### CODE REVIEW

**Comment by Felienne** [comment]
Wow @fRedelaar! This is AMAZING and so cool, and so supervaluable for kids!

The only thing I think we want to remove is the empty program warning in this mode, because that is a bit weird? (In general I am not sure we want to keep that warning)

**Comment by Felienne** [comment]
Ow just a tiny thing (sure you can fix this too!) the turtle canvas refreshes on each step, which is a bit confusing:

https://user-images.githubusercontent.com/1003685/162810427-67a91464-21a5-4d53-bdec-cfd05af88c8d.mov

**Comment by fRedelaar** [comment]
> Wow @fRedelaar! This is AMAZING and so cool, and so supervaluable for kids!
> 
> The only thing I think we want to remove is the empty program warning in this mode, because that is a bit weird? (In general I am not sure we want to keep that warning)

Thank you @Felienne ! I've removed the empty program warning in this mode :). About Turtle... I unfortunately don't know how to fix it. The way it is built right now: it sends the Hedy code before and on the line that is being highlighted in the debugger, to the compiler/backend. It keeps repeating this every time the "⏩" button is clicked. 

Code like `random` for example is being regenerated each time the "⏩" button is clicked. In the last line, the output changed from

`appel
aardbei
appel`
to 
`aardbei
aardbei
aardbei
aardbei
`

https://user-images.githubusercontent.com/33595265/162949020-8501b6d6-fd0c-4546-809a-ad6d3aed43ac.mp4



We send Hedy code to the backend, which returns Python code and that is captured in Skulpt. From that point on its hard to do anything with it.

**Comment by Felienne** [comment]
> Thank you @Felienne ! I've removed the empty program warning in this mode :). About Turtle... I unfortunately don't know how to fix it. The way it is built right now: it sends the Hedy code before and on the line that is being highlighted in the debugger, to the compiler/backend. It keeps repeating this every time the "⏩" button is clicked.

Yes I understand that we rerun the code each time and that it is hard to fix that even for text with the random issue. But for the turtle, could we at least make it so that when the debugger is running, and turtle code is present, the turtle canvas stays in view and does not get hidden and reshown on each step?

**Comment by fRedelaar** [comment]
> Yes I understand that we rerun the code each time and that it is hard to fix that even for text with the random issue. But for the turtle, could we at least make it so that when the debugger is running, and turtle code is present, the turtle canvas stays in view and does not get hidden and reshown on each step?

Ah! I misunderstood our conversion earlier. Sorry about that. What you want is definitely possible! I've just pushed a commit that solves it. The turtle canvas will not be reloaded anymore on each step.

**Comment by Felienne** [comment]
> > Yes I understand that we rerun the code each time and that it is hard to fix that even for text with the random issue. But for the turtle, could we at least make it so that when the debugger is running, and turtle code is present, the turtle canvas stays in view and does not get hidden and reshown on each step?
> 
> Ah! I misunderstood our conversion earlier. Sorry about that. What you want is definitely possible! I've just pushed a commit that solves it. The turtle canvas will not be reloaded anymore on each step.

Cool! I will make a plan for how to integrate and deploy this when I am back from my holiday.

**Comment by Felienne** [comment]
Hi @fRedelaar!

I wanted to check this out to think about the integration, but it seems the button is no longer there:

image


Maybe I made a mistake in merging? Could you have a peek?

**Comment by fRedelaar** [comment]
> Hi @fRedelaar!
> 
> I wanted to check this out to think about the integration, but it seems the button is no longer there:
> 
> image
> 
> Maybe I made a mistake in merging? Could you have a peek?

Hi! Typing from phone sorry about the formatting:

In ‘static/js/app.ts’ in line 1034

var step_debugger = false;

**Comment by Felienne** [comment]
Thanks for the quick answer @fRedelaar!

I played with the debugger a bit more and once we start having repeat blocks over multiple lines, we run into some issues with our one line per step approach:

image

The first line here cannot be executed in isolation, because the code then does not work (and gives an ugly error but that is not this PR's fault, logged separately in #2590)

It would be nicest (but super hard!) to really execute all lines of the body one by one.... but I guess we might also relax the grammar to allow this to parse so we can use the debugger here (tagging @boryanagoncharenko so she can think about this too)

Alternatively (if we want to launch this now) we can also only support it until level 7 as a way to keep this open not all too long.

**Comment by Felienne** [comment]
Making this into a draft util we figure out what to do with the debugger in level 8 and up

**Comment by fRedelaar** [comment]
Today during a meeting with @Felienne we decided to make the debugger available from level 1 to 7. From level 8 on, the debugger functionality is hidden. I've solved the merge conflicts and made the needed changes to hide the debugger from level 8 on.

**Comment by fRedelaar** [comment]
Found a bug, converting back to draft.

**Comment by fRedelaar** [comment]
Should be ready for review :)

**Review by Felienne — APPROVED** [review]
Ready to go @fRedelaar!!

You can test this on [hedy-alpha](https://hedy-alpha.herokuapp.com/) in a few minutes!

**Comment by Felienne** [comment]
Ow and not that this is merged, could you write a small explanation in https://github.com/Felienne/hedy/discussions/categories/announcements so teachers know what this is? :)

**Comment by fRedelaar** [comment]
> Ready to go @fRedelaar!!
> 
> You can test this on [hedy-alpha](https://hedy-alpha.herokuapp.com/) in a few minutes!

It looks good to me! :) Thanks for checking it out

**Comment by fRedelaar** [comment]
> Ow and not that this is merged, could you write a small explanation in https://github.com/Felienne/hedy/discussions/categories/announcements so teachers know what this is? :)

I've written a text, but I cannot select the "announcement" category. Should I post it anyways, and that @Felienne moves it to announcements? 
image

**Pull request merged**
