### PR TITLE
[FIX] Fixes incorrect parsons title translation

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
Fixes incorrect merging whoopsie where we accidentally kept the Babel fuzzy guess.

**Fixes _issue or discussion number_**

Always link the number of the issue or of the discussion that your pr concerns.

**How to test**

* If this is a UI change: _describe how to run your code to see it in action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example_
* If this is a language change: _add a few tests showing the difference_

**Checklist**
Done? Check if you have it all in place using this list:*
  
- [ ] Describes changes in the format above (present tense)
- [ ] Links to an existing issue or discussion 
- [ ] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by Felienne** [comment]
This fix en and es but it does not fix the title in other languages I think?

image

**Comment by Felienne** [comment]
Or will Weblate now overwrite this (I guess you will figure this out on Wednesday with @Mark-Giesen?)

**Comment by TiBiBa** [comment]
@Felienne This should be fixed!
Schermafbeelding 2022-07-04 om 11 42 01

**Comment by Felienne** [comment]
@TiBiBa Conflicts on this one again 😭  I will merge weblate again, can you then fix these?

**Review by Felienne — APPROVED** [review]

**Comment by Felienne** [comment]
This can be merged once the conflicts are fixed

**Pull request merged**
