### PR TITLE
[FEATURE] Enables users to set a preferred keyword language on their profile

### LINKED ISSUE #2008: [UI idea] Enable users to set preferred keyword language in profile
**Idea incl level**
With the support of keywords in different languages it would be nice if we enable users to select a preferred language. This way we don't have to show the dropdown overlay menu on each editor and simply always show language. We might have to think about some issues:

- What do we do with all starting code / adventures -> currently all with English keywords
- Do we parse them on each retrieval -> This is really expensive

Do you have a suggestion how we can efficiently implement this? @Felienne

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we implement the structure to enable users to set and change a preferred keyword language. With the implementation of multi-language keywords users are currently able to switch between their chosen language (if supported) and English through a language switcher on the code editor. With this PR users can set a fixed preferred command language, which is stored on their profile.

**Fix for**
This PR addresses, but does not fully fix #2008.

**How to test**
This is mostly a back-end structural PR and does not influence the user experience much. Navigate to the signup page and notice the new input field on `preferred keyword language`. Verify that this field is working as well as on the profile page where the user settings can be updated. If a language is chosen the language switcher on the front-end is no longer shown. 

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] Links to an existing issue or discussion (if not, create an issue first)
- [ ] Describes changes clear in the format above (present tense, no subject)
- [ ] Has a "how to test" section
- [ ] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by TiBiBa** [comment]
@Felienne This PR is ready for review! It creates the structure enabling users to select a preferred keyword language and for us to keep track of this value in the back-end. This should be the starting-point for the multi-language adventures.

**Comment by Felienne** [comment]
Hi @TiBiBa!

I just tested this but it does not seem to work entirely correct yet. I can set a language in my profile and that does remove all switch buttons, however, the code snippets remain in English:

image

I tried setting my language to Spanish and to Dutch bit the snippets remain to use English keywords for both settings.

Interestingly enough, when I set my language to Spanish, and then log out... the options become Es and Nl:

image

**Comment by Felienne** [comment]
Ow maybe the snippets are not yet meant to be shown in the set language? Reading the PR text again I am not sure it was supposed to already work, but at least the weird logging out behaviour is not what we want.

**Review by Felienne — CHANGES_REQUESTED** [review]
See above

**Comment by TiBiBa** [comment]
> Ow maybe the snippets are not yet meant to be shown in the set language? Reading the PR text again I am not sure it was supposed to already work, but at least the weird logging out behaviour is not what we want.

The goal of this PR was to only implement the back-end structure for storing the preferred keyword language as we still have to figure out an efficient way to show all code snippets in the selected language (parsing is expensive, translating complex).

**Comment by TiBiBa** [comment]
The switcher should be fixed! The back-end structure is complete (users are able to set a keyword language), but the snippet are still all loaded in English. I think we need to have some discussion and a separate issue to solve that problem.

**Comment by Felienne** [comment]
> The switcher should be fixed! The back-end structure is complete (users are able to set a keyword language), but the snippet are still all loaded in English. I think we need to have some discussion and a separate issue to solve that problem.

Ok, got it! Then this can be merged (will do so later today)

For the front-end implementation, let's discuss indeed, I have some ideas but they might not scale well :)

**Comment by Felienne** [comment]
Yes the weirs es/nl issue is gone now!

One question, why are Arabic and French not the list, we have keywords for that as well (although not 100% complete for Ar)

image

**Comment by TiBiBa** [comment]
> Yes the weirs es/nl issue is gone now!
> 
> One question, why are Arabic and French not the list, we have keywords for that as well (although not 100% complete for Ar)
> 
> image

Didn't know that! We have a variable `ALL_KEYWORD_LANGUAGES` in `app.py` (line 72). We can simply add them there and it should all work automatically.

**Comment by Felienne** [comment]
> > Yes the weirs es/nl issue is gone now!
> > One question, why are Arabic and French not the list, we have keywords for that as well (although not 100% complete for Ar)
> > image
> 
> Didn't know that! We have a variable `ALL_KEYWORD_LANGUAGES` in `app.py` (line 72). We can simply add them there and it should all work automatically.

Ah good to know, I would have added it there! (adding keywords is still manual work by me and that shows haha)

**Review by Felienne — APPROVED** [review]

**Pull request merged**
