### PR TITLE
Aflatoun global money week adventure

### PR DESCRIPTION
**Pull request by MarleenGilsing**
Adds a new adventure in association with Aflatoun for the Global Money Week.

### CODE REVIEW

**Comment by MarleenGilsing** [comment]
@Felienne This is what I can up with after the meeting with Mahbobah today. What do you think? She asked if we could feature it a bit more prominently during the Global Money Week and de week van het geld, so I though maybe we could turn the tab green. @TiBiBa said he could easily do that.

**Comment by TiBiBa** [comment]
Do we want to turn the tab green on this PR or merge the adventure first and turn it on later? (Not sure when the 'week van het geld' starts).

**Comment by Felienne** [comment]
Week van het geld starts on March 28th, so this does not have to be merged (and deployed) before that

**Comment by TiBiBa** [comment]
Ready for merge!

Schermafbeelding 2022-03-22 om 17 41 20

**Comment by TiBiBa** [comment]
The 'week van het geld' starts today! Should we merge this already today or somewhere later this week?

**Review by TiBiBa — APPROVED** [review]

**Review by TiBiBa — CHANGES_REQUESTED** [review]
We do have to localize the keywords! Will fix that today.

**Review by TiBiBa — APPROVED** [review]

**Comment by TiBiBa** [comment]
If the tests pass this is ready to merge!

**Pull request merged**
