### PR TITLE
Fix for issue #1252

### PR DESCRIPTION
**Pull request by teundemast**
Retrieve english keywords when keywords for a language are not availabe (yet) 

Fixes issue #1252

### CODE REVIEW

**Comment by teundemast** [comment]
Because of recent commits, the language was not passed as an argument into the transpiler. This is fixed with the most recent commit and will be fixed if this pull request is accepted.

**Review by Felienne — CHANGES_REQUESTED** [review]
Hi all! In principle this works, but if we merge this, in the Duthc version, only Dutch programs can be parsed (f.e. only `drukaf hallo`) that is not ok for now because we do not have all other things in place (distance algo, explanations etc)

So can we put this behind a flag? Something like

```
if local_keywords_enabled:
.....
```

**Comment by teundemast** [comment]
Ah, ofcourse! We are working on #915, so English keywords can also be used when the specified language is Dutch. But for now,  with the most recent commit (made a typo in the name), I have added a flag.

**Comment by Felienne** [comment]
Hi @teundemast!

The PR is quite a bit behind because so many things changed in the meantime, sorry. Can you either fix the PR or start anew from a fresh branch of of main?

**Comment by teundemast** [comment]
Hi @Felienne, no problem! I will create a new PR.

**Pull request closed without merging**
