### PR TITLE
Change German definition of Hady

### PR DESCRIPTION
**Pull request by nichtich**
As a native speaker I stumbled upon the German definition of Hady as "graduelle Programmiersprache". The word "graduell" is very technical an rarely used in common language, especially not by children. Possible alternatives:

* *allmähliche Programmiersprache* - I like this, because it comes with a taste of "take-it-slowly", but the word is more used as adverb and it could also be misread as "programming language that is still being developed"
* *schrittweise Programmiersprache* - catches well the learning experience but could also be misread as "programming language with step-by-step execution"
* *abgestufte Programmiersprache* - this seems (roughly translated "stepwise") to be the most exact translation. The image that comes with this word is a staircase.

I also change minor wording in the rest of the text.

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks for your first Hedy contribution @nichtich! As a person with just a conversational level of German, it is hard to decide if this is the right word. Maybe @dpprdan can chime in here, he did most of the German translation work so far.

**Comment by Felienne** [comment]
Or maybe @StephanEggermont's German is close enough to native to give his opinion (or ask one of the native speakers in his household :D)

**Comment by dpprdan** [comment]
@nichtich Good point, I also noticed this again the other day. I think it's of those cases where it's difficult to come up with an _exact_ translation, especially one that is easily understood by kids. But "abgestuft" fits pretty well in my opinion. 

Another alternative would be "stufenweise" or "stufenweise fortschreitend" as in "eine stufenweise fortschreitende Programmiersprache" - a stepwise progressing programming language. 

@Felienne Are there any other gradual programming languages or is Hedy unique in this respect? I also wonder whether "gradual" is a word commonly used by kids in English (or "gradueel" in Dutch for that matter) or whether it is jargon there, too?

**Comment by StephanEggermont** [comment]
Perhaps use “mitwachsende”? (Katja says hi)

**Comment by Felienne** [comment]
> @nichtich Good point, I also noticed this again the other day. I think it's of those cases where it's difficult to come up with an _exact_ translation, especially one that is easily understood by kids. But "abgestuft" fits pretty well in my opinion.
> 
> Another alternative would be "stufenweise" or "stufenweise fortschreitend" as in "eine stufenweise fortschreitende Programmiersprache" - a stepwise progressing programming language.

Thanks for chiming in!!

> @Felienne Are there any other gradual programming languages or is Hedy unique in this respect? I also wonder whether "gradual" is a word commonly used by kids in English (or "gradueel" in Dutch for that matter) or whether it is jargon there, too?

Yeah, you are right, it is very much a jargon word, I stole it from [gradual typing](https://en.wikipedia.org/wiki/Gradual_typing) As far as I know there are not other languages that work like Hedy and that call themselves gradual languages.

In Dutch too "gradueel" is an uncommon and quite technically sounding word; in English I feel it is a more commonly used word (although I am not a native speaker). Hence, I think it is totally fine if we translate it to a different, more clear, word in German or other languages.

**Comment by krono** [comment]
@StephanEggermont summoned me…

I've pondered the term for a moment. The "gradual" part for me sounds along the line of "gradient" (like in a color gradient).
But I think "mitwachsend" is the best fit here. I also thought of this before reading Stephan's comment. 
I'm just thinking of these desks for children that are height adjustable and hence can be made fit fort the changing needs of a growing child. An often used term in that area is indeed "mitwachsend"  and if Hedy has properties that make it "adaptable to the needs of growing developers", by all means, "mitwachsend" is a nice fit.

**Comment by dpprdan** [comment]
Agree with @krono, "mitwachsende Programmiersprache" is the best term, yet. Easily understandable, no unintended/double meaning (that I can think of at least), and captures the intention nicely.

**Comment by Felienne** [comment]
> Agree with @krono, "mitwachsende Programmiersprache" is the best term, yet. Easily understandable, no unintended/double meaning (that I can think of at least), and captures the intention nicely.

I trust you German speakers of course, so let's do "mitwachsende". Do you want to update this PR yourself @nichtich?

**Review by Felienne — CHANGES_REQUESTED** [review]
graduelle -> mitwachsende

**Comment by nichtich** [comment]
I've changed the definition to use "mitwachsende" but hat do add further changes: As mitwachsend" is based on a verb I did not write "ist mitwachsend" but "wächst mit" (*grows together*) resulting in more changes in the last paragraph, including an introduction of "Programmcode" as asked for at <https://github.com/Felienne/hedy/discussions/1590>.

**Review by Felienne — APPROVED** [review]
Thanks for this @nichtich and the other German speakers that chimed in!!

**Comment by dpprdan** [comment]
Hedy has been featured on heise.de today, with "mitwachsende" 😂 
[Hedy: die "mitwachsende" Programmiersprache | heise online](https://www.heise.de/news/Hedy-die-mitwachsende-Programmiersprache-6336264.html)

**Comment by Felienne** [comment]
> Hedy has been featured on heise.de today, with "mitwachsende" 😂 [Hedy: die "mitwachsende" Programmiersprache | heise online](https://www.heise.de/news/Hedy-die-mitwachsende-Programmiersprache-6336264.html)

I was wondering why we had large amounts of traffic from Germany!! Thanks for letting us know.

**Pull request merged**
