### PR TITLE
Count programs per user

### LINKED ISSUE #216: Add #programs per user
Can we have the number of programs behind each users (to quickly find interesting users to explore)

### PR DESCRIPTION
**Pull request by fpereiro**
- Count programs per user.
- Contains script to add current count to all existing users. The script is idempotent although we should remove it soon to avoid doing a lot of calls to DynamoDB.
- Closes #216

### CODE REVIEW

**Comment by Felienne** [comment]
> The script is idempotent although we should remove it soon to avoid doing a lot of calls to DynamoDB.

I am not sure what you mean here, do you mean we don't cache the values and run an (expensive) query each time we load the page?

**Comment by fpereiro** [comment]
Hi! It means that every time that Hedy is started, the script to load the count will run - after the first time, we can remove it. But if the script runs multiple times, apart from a few extra DB reads, everything will be consistent.

We store the program count in each user so that each time we open the admin we don't have to count the programs for each user - the reasons being both performance and saving on DB queries.

**Comment by Felienne** [comment]
I am still not sure what you mean (esp with "when Hedy starts", do you mean: when it is deployed?")

Let me know when I can accept this, because the way I understand it is that right after you want to remove the init script for the counts?

**Comment by fpereiro** [comment]
Sorry for the lack of clarity :) I meant that this script to update the db will run every time that Hedy is deployed - that is, when the app starts for the first time.

I can do a separate PR afterwards to remove this script, once we check that the values have been updated in the DB.

**Comment by Felienne** [comment]
Yes, got it now! I'll see the other one in a new branch. Can you merge this one yourself, after the new version of the tests? Because I fear it will not work otherwise because the new tests will run and are broken.

**Pull request merged**
