### PR TITLE
I bought a fancy new domain! 

### PR DESCRIPTION
**Pull request by Felienne**
And updated our email address everywhere which a search and replace, but this needs a good check if it does not break anything (email sending? error messages in which this occurs?)

### CODE REVIEW

**Comment by arjank** [comment]
Unfortunately Arabic (and rtl in general) is a bit too tricky for me, but you should check line 2061 of `translations/ar/LC_MESSAGES/messages.po`. And no, I can't comment on that line in the pull request.

There are also 3 references to your Gmail address.

Oh, and congrats on the new fancy shiny domain :smiley: 

PS: I haven't tested anything.

**Review by arjank — CHANGES_REQUESTED** [review]
Unfortunately Arabic (and rtl in general) is a bit too tricky for me, but you should check line 2061 of `translations/ar/LC_MESSAGES/messages.po`. And no, I can't comment on that line in the pull request.

There are also 3 references to your Gmail address.

Oh, and congrats on the new fancy shiny domain :smiley:

PS: I haven't tested anything.

**Comment by Felienne** [comment]
> Unfortunately Arabic (and rtl in general) is a bit too tricky for me, but you should check line 2061 of `translations/ar/LC_MESSAGES/messages.po`. And no, I can't comment on that line in the pull request.
> 
> There are also 3 references to your Gmail address.
> 
> Oh, and congrats on the new fancy shiny domain 😃
> 
> PS: I haven't tested anything.

Good catch!! The gmails are for Heroku, they should stay the same. 

But I guess we should test this on alpha if it does no screw up any actual email sending.

**Review by arjank — APPROVED** [review]

**Comment by arjank** [comment]
> > Unfortunately Arabic (and rtl in general) is a bit too tricky for me, but you should check line 2061 of `translations/ar/LC_MESSAGES/messages.po`. And no, I can't comment on that line in the pull request.
> > There are also 3 references to your Gmail address.
> > Oh, and congrats on the new fancy shiny domain smiley
> > PS: I haven't tested anything.
> 
> Good catch!! The gmails are for Heroku, they should stay the same.
> 
> But I guess we should test this on alpha if it does no screw up any actual email sending.

We probably should configure SPF records to prevent email being flagged as spam, but that is domain configuration and not directly related to this ticket.

**Pull request merged**
