### PR TITLE
Localizing translate characters

### PR DESCRIPTION
**Pull request by teundemast**
**Description**
With this PR the function 'translate_characters' is localized, which means that instead of the following error message: 
translate_characters

The programmer will recieve this error message: 
translate_characters2

Fixes issue #1302

### CODE REVIEW

**Comment by Felienne** [comment]
Going to tag @boryanagoncharenko here, because I think we should have already supported this before (we already have the translations) 

I think you might have found a bug rather than a missing feature. 

Can you share some code snippets where you got this error originally so I can look into it?

**Comment by Felienne** [comment]
Update, the function `def translate_error(code, translations, arguments)` in app.py should handle this

**Comment by teundemast** [comment]
Ah totally missed that, I just assumed it was not translated because the function just returned an English word. Sorry about that!

**Comment by Felienne** [comment]
Teah I gues my comment there also did not help! 

WOuld still love to see the code though attached to your screenshot because that should still be fixed!

**Comment by teundemast** [comment]
It was some code I wrote in my local environment on the branch from this pull request, but with local keywords disabled. I just assumed I would get the same error when I would run the code on the main branch 😅. So no worries, all good!

**Pull request closed without merging**
