### PR TITLE
Show variables and values live #1329

### PR DESCRIPTION
**Pull request by fRedelaar**
For issue #1329, I've created a box that can display the variables and their values. WIP Draft! **(This work is for a student project at Leiden University)**. Still needs lots of work to make it more fitting in the Hedy theme and overall UX friendly.

**How to test**
Go to any level that uses variables. Level 9, calculator for example. Click on "variables" such as the screenshot below and the list will expand/collapse.
image

### CODE REVIEW

**Comment by fRedelaar** [comment]
Added a feature flag (false for now). The project is not finished, but it could be a good idea to merge in small portions to avoid merge conflicts.

**Comment by Felienne** [comment]
> **How to test** Go to any level that uses variables. Level 9, calculator for example. Click on "variables" such as the screenshot below and the list will expand/collapse. image

Thanks for the feature flag @fRedelaar! I guess the how to test then should be that all works as before?

**Comment by Felienne** [comment]
(it does seem all is still entirely as before!)

**Comment by fRedelaar** [comment]
@Felienne yes, the only addition was the feature flag :). It can be tested by setting the flag to true.

**Review by Felienne — APPROVED** [review]

**Comment by Felienne** [comment]
Hmmm typescript is not happy with the feature flag, it is a bit too smart for our usecase :(

image

**Comment by Felienne** [comment]
We could do something slightly cleverer, like pick a release date in the far future (say, July 2022 when you are done for sure) and compare today's date to the release date?

**Comment by fRedelaar** [comment]
> We could do something slightly cleverer, like pick a release date in the far future (say, July 2022 when you are done for sure) and compare today's date to the release date?

Good idea! I will try fixing the failed unit tests, using this idea :)

**Comment by fRedelaar** [comment]
After some closer inspection, I found out that I had to edit some of the Typescript - still really liked your idea Felienne!

**Pull request merged**
