### PR TITLE
[BUG FIX] Parsons exercises with indentation work as expected

### LINKED ISSUE #2939: [PARSONS] Spaces in Parsons are removed causing programs to not run
Some lines in code should be indented and I have just added that in the yamls (for en/nl, in #2940):

image

But these spaces are removed when presenting, so the correct (green) code does not run:

image

Can we change the code (or the yaml's?) so that the spaces stick?

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we fix the parsons exercises with indentation that didn't work as expected yet. We fix this by changing the YAML structure to make sure the whitespaces are preserved. We only fix this for the English YAML and the translated NL exercises as the non-translated ones should automatically be overwritten by Weblate.
Schermafbeelding 2022-06-23 om 13 43 01

**Fixes**
This PR fixes #2939.

**How to test**
Navigate to level 8 and verify that the parsons exercise with indentation is working as expected.

### CODE REVIEW

**Comment by TiBiBa** [comment]
> I guess this makes my yaml changes in #2940 obsolete?

I think it does, however I didn't make any textual changes in this PR.

**Comment by TiBiBa** [comment]
@Felienne conflicts are solved, should be ready to merge!

**Comment by Felienne** [comment]
> Tried to test this locally, but didn't get it to work. Either it's not fixed, or I need to do more than just checkout the branch and refresh the browser. I guess it's the latter.

Maybe you already know this (but someone had to show it to me also recently, so maybe not) Chrome allows you to disable caching in dev. mode which has often helped me:

image

**Review by Felienne — APPROVED** [review]
For me it works in Chrome and FF!

**Comment by Felienne** [comment]
image

**Comment by arjank** [comment]
> > Tried to test this locally, but didn't get it to work. Either it's not fixed, or I need to do more than just checkout the branch and refresh the browser. I guess it's the latter.
> 
> Maybe you already know this (but someone had to show it to me also recently, so maybe not) Chrome allows you to disable caching in dev. mode which has often helped me:
> 
> image

Disabling the browser cache didn't solve the problem for me. But it was solved after a restart of the webserver (forced by an update of PyCharm). Not sure what caused the issue, but at least there's a workaround if it shows up again.

**Pull request merged**
