### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Hedy/Adventures](https://hosted.weblate.org/projects/hedy/adventures/).

It also includes following components:

* [Hedy/Webpages](https://hosted.weblate.org/projects/hedy/webpages/)

* [Hedy/Parsons](https://hosted.weblate.org/projects/hedy/parsons/)

* [Hedy/Commands](https://hosted.weblate.org/projects/hedy/commands/)

* [Hedy/client-messages](https://hosted.weblate.org/projects/hedy/client-messages/)

* [Hedy/Quizzes](https://hosted.weblate.org/projects/hedy/quizzes/)

* [Hedy/Achievements](https://hosted.weblate.org/projects/hedy/achievements/)

* [Hedy/Texts](https://hosted.weblate.org/projects/hedy/web-texts/)

* [Hedy/Keywords](https://hosted.weblate.org/projects/hedy/keywords/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Felienne** [comment]
Hmmm this gives an interesting Babel issue!

image

@TiBiBa do you understand what goes wrong here?

**Comment by TiBiBa** [comment]
> Hmmm this gives an interesting Babel issue!
> 
> image
> 
> @TiBiBa do you understand what goes wrong here?

I think this happens due to the re-writing of the GitHub pipeline. Now we compile the translations on the pipeline, but "tn" doesn't exist yet!

**Comment by Felienne** [comment]
> I think this happens due to the re-writing of the GitHub pipeline. Now we compile the translations on the pipeline, but "tn" doesn't exist yet!

Ah got it! Is there a change we can make to fix this? If I compile the babel locally it still fails, it seems :(

**Comment by TiBiBa** [comment]
> > I think this happens due to the re-writing of the GitHub pipeline. Now we compile the translations on the pipeline, but "tn" doesn't exist yet!
> 
> Ah got it! Is there a change we can make to fix this? If I compile the babel locally it still fails, it seems :(

Weird! Will take a look

**Comment by Felienne** [comment]
Ow no..... I found the issue with a little bit of help from @rix0rrr.... Turns out... Babel does not support Tswana:

image (contents of the folder of site-packages/babel/locale-data)

This is, of course, only a problem for the babel strings, not for all the yamls. 

Can we make a patch @TiBiBa where we load English for language code tn for babel (while we wait for them to fix a patch, if that ever happens) but serve the yamls as normally.

**Comment by TiBiBa** [comment]
> Ow no..... I found the issue with a little bit of help from @rix0rrr.... Turns out... Babel does not support Tswana:
> 
> 
> 
> image 
> 
> 
> 
> (shown are the contents of the folder of site-packages/babel/locale-data, note there is nothing starting with tn)
> 
> 
> 
> This is, of course, only a problem for the babel strings, not for all the yamls. 
> 
> 
> 
> Can we make a patch @TiBiBa where we load English for language code tn for babel (while we wait for them to fix a patch, if that ever happens) but serve the yamls as normally.
> 
> 
> 
> 

Will do! We can make an issue on the Babel repo as well, will look into this.

**Comment by TiBiBa** [comment]
@Felienne #3141 should fix this issue! It is a bit of a bucket fix as we check if a language is in a manual created "Non Babel" list. It would be nice to verify this automatically by retrieving all Babel supported languages from the library, but couldn't find a nice way to fix this.

This should do for now so we can merge this new language.

**Comment by Felienne** [comment]
hmmmm seems #3141 does not yet fully fix the problem @TiBiBa :(

**Comment by TiBiBa** [comment]
Just raised this issue here python-babel/babel#899

**Comment by Felienne** [comment]
I think I found the other issue @TiBiBa!

**Pull request merged**
