### PR TITLE
Translating keywords in yaml files (adventures and level-defaults) 

### PR DESCRIPTION
**Pull request by teundemast**
With this PR, @FlorisHessels and I added 2 new transform functions in the yaml_transformer.py. These functions make it possible to translate the keywords in the yaml files to local keywords. Fixes issue #1256 

When we were working on this, we discovered some errors in the translations and in the translation structure. Those will also be fixed with this PR.

We will convert this PR to a draft request since the transform functions have some imperfections. Namely,

- If there is a word like 'to' in for example an intro text (in code this works fine), it is impossible to know if it should be translated to 'tot' or 'toe aan' in Dutch. So we think this should be translated manually. 
- If there is a word like 'ask' in a text but it is contained with ` `` `, than it won't be translated. 
- If there are multiple words in a text inside the ` `` ` the transformer function won't translate these words since most of the times this is invalid code. Thus, we can not use the current translation structure for this because that only accepts valid code.
- There are some pieces of code in 'Vooruitblik' which are invalid code as mentioned in issue #1506. So we cannot translate this for the same reason above. That's why, if the transform functions are used right now with current Dutch yaml, they will break. 
- If we execute the transform functions right now, the transformed yaml file won't have the same structure as the original yaml file. Namely, new lines will be replaced with \n in the transformed yaml file. We are not sure if there is a way to fix this. However, this has no effect on the website itself. 

For now, we have only tested the transform functions for Dutch.

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks for this awesome piece of work team!!

> There are some pieces of code in 'Vooruitblik' which are invalid code as mentioned in issue [BUG] The example codes in what's next adventures don't always work #1506. So we cannot translate this for the same reason above. That's why, if the transform functions are used right now with current Dutch yaml, they will break.

Yeah that is ok! We can fix those examples and then run this code

> * If we execute the transform functions right now, the transformed yaml file won't have the same structure as the original yaml file. Namely, new lines will be replaced with \n in the transformed yaml file. We are not sure if there is a way to fix this. However, this has no effect on the website itself.

Yeah I know this issue, it happens when you just dump yamls. You can use the ruamel version to write used in other places of the code bae as well to avoid that issue.

**Comment by teundemast** [comment]
Hi @Felienne, today is the deadline for delivering our product. We have decided to not continue with this issue, because we don't have time to do so. Some of our team members are going to work on their issues: issue #909 and issue #1498. 

Shall we leave this as a draft request or transform it into a Pull Request?

**Comment by Felienne** [comment]
> Hi @Felienne, today is the deadline for delivering our product. We have decided to not continue with this issue, because we don't have time to do so. Some of our team members are going to work on their issues: issue #909 and issue #1498.
> 
> Shall we leave this as a draft request or transform it into a Pull Request?

You might leave it as is, I can finish it myself.

Is the only thing left to make sure that the yaml output looks readable or were there other things still open?

**Comment by Felienne** [comment]
Thanks for the clarification! We will pick this up further in the Core Team!

**Pull request closed without merging**
