### PR TITLE
[VALIDATION] Improved mail sending process error handling

### LINKED ISSUE #3019: Add additional validation for mail sending template
**Description**
We recently introduced a signup breaking bug by a seemingly innocent change: the adding of a translatable alt attribute to the mail template. This shows how vulnerable our mail sending process is and we should improve this. e2e testing of mail sending is hard, but we can surround these sendings with try-catch and verify the correctness of the steps.

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we add some extra try-except catches around the mail sending templates. Making sure that the user experience doesn't crash or behaves unexpectedly when an error occurs during mail sending. In all cases we now return an error message explaining that the mail sending went wrong but the changes are still processed.

**Fixes**
This PR fixes #3019.

**How to test**
We can only test this on Alpha as we can't check the mail sending process locally.

### CODE REVIEW

**Review by Felienne — APPROVED** [review]
Looks good and does not seem to break anything locally

**Comment by Felienne** [comment]
Good luck fixing the conflicts @TiBiBa :D

**Comment by TiBiBa** [comment]
> Good luck fixing the conflicts @TiBiBa :D

Will take a look!

**Comment by TiBiBa** [comment]
Should be fixed (I hope...)

**Pull request merged**
