### PR TITLE
Radio buttons on sign up form are not aligned with UI

### LINKED ISSUE #1150: [BUG] Programming experience on sign-up is shifted
**Describe the bug**
When creating an account the question for programming experience with radio-buttons is not aligned with the other inputs. See example screenshot below.

**Add a screenshot (optional)**
Schermafbeelding 2021-11-03 om 10 05 33

**Expected behavior**
The question and corresponding radio buttons should be in line with the rest of the inputs of the form.

**What machine and browser you were using (optional)**
MacOS 11.6 Safari 15.0

### PR DESCRIPTION
**Pull request by TiBiBa**
Provide a general summary of your changes in the Title of the PR

**Description**
The radio buttons of the question on programming experience on the sign-up page are not correctly aligned with the rest of the form. In this UI we change the structure of the form to improve the visualization of the questions. See screenshots below for clarification.

**Old view**
Schermafbeelding 2021-11-03 om 14 45 35

**New view**
Schermafbeelding 2021-11-03 om 14 45 07

**Fix for**
This PR fixed #1150.

**How to test**
Visit sign-up page and verify that the radio buttons are aligned correctly.

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [x] Links to an existing issue or discussion (if not, create an issue first)
- [x] Describes changes clear in the format above (present tense, no subject)
- [x] Has a "how to test" section
- [x] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by Felienne** [comment]
This surely looks nicer than what we have, but it would be *even* nicer if the text was aligned with the text above, is that possible or is that too cumbersome?

**Comment by TiBiBa** [comment]
> This surely looks nicer than what we have, but it would be _even_ nicer if the text was aligned with the text above, is that possible or is that too cumbersome?

Agree! I've been struggling quite a bit with improving the UI of this form. Will give it another look to make it all aligned.

**Comment by TiBiBa** [comment]
I've converted the into a draft for now until I've a better solution

**Comment by TiBiBa** [comment]
I've completely restructured the form UI and it should all be working correctly now. Below some screenshots for clarification. I'll open the PR again because I think it is ready to be merged.

Schermafbeelding 2021-11-04 om 11 48 23
Schermafbeelding 2021-11-04 om 11 48 31

**Comment by Felienne** [comment]
> I've completely restructured the form UI and it should all be working correctly now. Below some screenshots for clarification. I'll open the PR again because I think it is ready to be merged.
> 
> Schermafbeelding 2021-11-04 om 11 48 23 Schermafbeelding 2021-11-04 om 11 48 31

Looks great!! The only thing is that for me locally the newsletter button is not aligned:

image

Not sure why that happens, is this only for me?

**Comment by TiBiBa** [comment]
That's weird! For me it looks like this:
Schermafbeelding 2021-11-05 om 14 29 40

Will take a look if I made a styling mistake somewhere

**Comment by Felienne** [comment]
Shall I merge to alpha and see if the issue remains? It is not a big deal (I am on macos/Chrome btw)

**Comment by TiBiBa** [comment]
I might have found a solution, will try it out now on chrome

**Comment by TiBiBa** [comment]
Fixed with last commit!

**Comment by Felienne** [comment]
Fixed indeed!!

image

**Review by Felienne — APPROVED** [review]

**Pull request merged**
