### PR TITLE
Fixed the error where an automatic error was given in level 10 with indents

### PR DESCRIPTION
**Pull request by LauraTSD**
The error was in the start code which resulted in a lot of errors in user programs.

### CODE REVIEW

**Comment by LauraTSD** [comment]
Fixes error https://github.com/Felienne/hedy/issues/501

**Comment by Felienne** [comment]
Well done @LauraTSD! Did you find this error through the logs?

**Comment by LauraTSD** [comment]
> Well done @LauraTSD! Did you find this error through the logs?

Yes I did! 30.53% of the errors made of level 10 were caused by this error.

**Comment by Felienne** [comment]
Great catch!! And I was wondering why I did not see it but that is because I only test in Dutch... So I learned a good lesson too!!!

**Pull request merged**
