### PR TITLE
Fixes for text consistency, marked commands and missing examples in Commands

### PR DESCRIPTION
**Pull request by mgmalheiros**
This is my suggested fixes for the commands in English (I believe this is the correct way of altering it, not through Weblate).

Summary:
- Added missing initial caps and full stop for explanations.
- Removed the command curly brackets in a few places, like "{ask} for a calculation and check whether it is correct."
- Added curly brackets to many {else}
- All examples now begin with "Example: "
- Added a few missing examples
- One code snippet was incorrect: "answer = {ask} 'What is 20 plus 20?'"

Of course, if there is a better way to contribute just ask and I will resubmit this pull request.

Thank you for the wonderful Hedy language!

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks for all the fixes @mgmalheiros!! Making changes both here and in Weblate are fine, we will now just have to merge Webalte before this to prevent conflicts but I can take care of that. Let us know if you need any more help in contributing!

**Comment by Felienne** [comment]
Sorry for updating but not merging your PR @mgmalheiros! We are doing a live demo tomorrow at a conference so we are a bit hesitant to merge things but I also want to prevent conflicts later on!

**Comment by mgmalheiros** [comment]
Of course, no problem at all!

There is no hurry and obviously feel free to discard any suggested updates that do not seem ok.

If fine-grained suggestions for the source strings are easier to handle through Weblate, I can happily sent through there.

**Review by Felienne — APPROVED** [review]
ok, we should be ready to go! This now also closes #2904.

**Comment by Felienne** [comment]
Thanks again for your first Hedy contribution @mgmalheiros!! If you want to help out more, do let us now here or on our Discord!

**Pull request merged**
