### PR TITLE
Issue 162

### PR DESCRIPTION
**Pull request by MarinusVanDijk**
Please find enclosed the changes for issue 162.

Unit test added for helper functions and added closest_command() function.

Death code re-used for resolving 'abc' -> 'ask'.

I will first test the repair method in full, issue a ticket for improvements if necessary on my behave.

### CODE REVIEW

**Comment by Felienne** [comment]
@MarinusVanDijk Thanks for the fix! I am not sure what you mean by "I will first test the repair method in full, issue a ticket for improvements if necessary on my behave." 

Does that mean you are still testing/working on this, or can we merge this current version?

**Comment by MarinusVanDijk** [comment]
@Felienne You are welcome! Let us merge this one because it is an solution to the #162 problem anyway. 

I would like to test the existing repair method in full before coming with suggestions for improvement.

I have made another repair method which normalizes the distance measure in order to check for an maximum, upper bound distance.

In this way you can configure the repair distance such that errors will stay low in the syntax.

But I can imaging there are more important issues to take care of. Please indicate if so.

**Comment by fpereiro** [comment]
Hi @MarinusVanDijk ! I reviewed it and tested locally and it works well. Thank you for this!

Do you need to add further improvements? If not, I can already merge it. Let me know.

Thank you!

**Comment by fpereiro** [comment]
Merged, thank you!

**Pull request merged**
