### PR TITLE
Basic improvements to sharing/unsharing

### LINKED ISSUE #480: Missing things for deploying basic program sharing
- Prompt to let kids know that their sharing/making public was successful.
- Copy share link to clipboard.
- Internationalize texts (either translations or placeholders) so that they are available everywhere.

### PR DESCRIPTION
**Pull request by fpereiro**
- Alerts to give feedback when sharing/unsharing
- Add share in other languages
- Copy program link to clipboard.
- Closes #480

### CODE REVIEW

**Comment by Felienne** [comment]
@fpereiro Seems to be working ok! (merged so I can test at alpha)

Maybe in the message "Program shared successfully" we can make more kid friendly and more helpful into: 

"You can now show this program to the work! We have link to share copied to clipboard that you can paste."

**Comment by fpereiro** [comment]
Hi @Felienne ! Besides changing the message, do we want to copy the link to the clipboard already?

**Comment by Felienne** [comment]
Ah I thought we already did but if we don't yet, on clicking ok in "do you really want to share" we can place the link on the clipboard immediately. Saves kids a click!

**Comment by fpereiro** [comment]
> Ah I thought we already did but if we don't yet, on clicking ok in "do you really want to share" we can place the link on the clipboard immediately. Saves kids a click!

WIll do!

**Pull request merged**
