### PR TITLE
Solving the problem of over-coloring

### LINKED ISSUE #2279: Don't highlight ask/vraag at the beginning of the line in level over 3
In the last days some students noticed something confusing. In case you use Dutch with English commands and you use a Dutch word in your code that is coincidentally the translation of an English command, the word is highlighted in red as if it were a command. This happens more frequently than I initially thought. As an example, see the fortune adventure in level 4 (https://www.hedycode.com/hedy/4/#fortune) with the code `vraag is ask 'Wat wil je weten?'`. Would it be doable to implement an English-command-only option where users cannot switch to Dutch and no highlighting of Dutch translations of English commands?

_Originally posted by @OnnoEbbens in https://github.com/Felienne/hedy/discussions/2080#discussioncomment-2415140_

### PR DESCRIPTION
**Pull request by thjazi39**
To solve the problem of over highlighting I added a system that allows to add some rules, which allows to avoid highlighting a word before `ìs`
This is to be used with caution, because it can interfere with other rules that are generated, and create highlighting problems.

fix #2279 

**Result**
- before : image
- after : image

**How to test**
Check that the `ask` keyword is not recognized before `is`

**Addition in the test system**
Because you have to wait until you have an `is` keyword for the `ask` keyword not to be colored, I added an option in the test functions to disable the intermediary tests (consistency during word input)

image

### CODE REVIEW

**Review by Felienne — CHANGES_REQUESTED** [review]
The coloring of `ask` at the beginning of the line seems to indeed work but it is now also highlighted as a variable:

image

Also, probably a really small thing but we get an error in the js:

image

**Comment by thjazi39** [comment]
Now it should work!

It even works during line input!
image

**Comment by Felienne** [comment]
> Now it should work!
> 
> It even works during line input! image

Cool, will test this tomorrow!!

**Review by Felienne — APPROVED** [review]
Cool, this seems to work well now, tested for Dutch and English:

image

image

**Pull request merged**
