### PR TITLE
Adds fr keywords

### PR DESCRIPTION
**Pull request by Felienne**
Adds French keywords

**Fixes #1979**

**How to test**

Tests added for weird cases like keywords with spaces.

**Checklist**
Done? Check if you have it all in place using this list*
  
- [X] Describes changes in the format above (present tense)
- [X] Links to an existing issue or discussion 
- [X] Has a "How to test" section

* If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by Felienne** [comment]
Maybe you can have a look at whether this is correct @thjazi39?

**Comment by thjazi39** [comment]
ok, I confirm the validations!
I think that if `until` is stuck, while `while` and `if` are not, it's because in one case, we have an apostrophe, while in the 2 other cases, they are 2 distinct words.
If this is done on purpose, I think it's a good idea, and if not, we could standardize it by putting spaces (if supported by hedy)

**Comment by Felienne** [comment]
> ok, I confirm the validations! 

> I think that if `until` is stuck, while `while` and `if` are not, it's because in one case, we have an apostrophe, while in the 2 other cases, they are 2 distinct words. If this is done on purpose, I think it's a good idea, and if not, we could standardize it by putting spaces (if supported by hedy)

If you leave a comment on the code (go to :Files Changed) it will be easier for me to see what you refer to.

I am not sure I follow, we don't have `until`? 

In any case, spaces are supported! Where do you suggest we add them?

**Comment by thjazi39** [comment]
Sorry, I had translated the keywords, but I didn't think it would be a problem for the understanding (I modified the messages to be better!)

And while trying to comment the code, I realized that the `jusqu'à` has been changed to `à` so in the end, there is no problem!

On the other hand, it means that the command `_TO` has the same translation as `_TO_LIST` , and I don't know if this can be a problem

**Pull request merged**
