### PR TITLE
Adds all_commands function

### PR DESCRIPTION
**Pull request by Felienne**
To be used in program analysis, f.e. by the achievements

### CODE REVIEW

**Comment by Felienne** [comment]
Ready for you to use @TiBiBa!

**Comment by TiBiBa** [comment]
> Ready for you to use @TiBiBa!

Awesome, thanks! What is the best way to merge this branch into the achievements branch? (Never done that before)

**Comment by Felienne** [comment]
> > Ready for you to use @TiBiBa!
> 
> Awesome, thanks! What is the best way to merge this branch into the achievements branch? (Never done that before)

I guess the easiest way is to merg into main and then merge main into yours :D

**Comment by bjorn3** [comment]
If you click edit in the right corner you can change the base branch for this PR. This is the branch into which this PR will be merged.

---

image

---

image

**Comment by Felienne** [comment]
@TiBiBa You can merge main and get the `all_commands` function!

**Pull request merged**
