### PR TITLE
Removed 7-2 and reverted level 8

### PR DESCRIPTION
**Pull request by Tazaria**

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @Tazaria! I tried merging your code into main but some merge issues remain, can you make sure this PR is up to date with main?

**Comment by Tazaria** [comment]
Updated the fork. Not sure what the merge conflict was, as on my end there was none. Also don't pay attention to the mess surrounding level7-1.lark. Didn't realise it was still necessary and was a bit too hasty with the commit

**Comment by fpereiro** [comment]
@Felienne the merge conflicts seem to have faded away :)

**Comment by Felienne** [comment]
> @Felienne the merge conflicts seem to have faded away :)

Does that mean you approve the PR @fpereiro?

**Comment by fpereiro** [comment]
Hi @Tazaria ! It is working well for me. However, I see that level 8 in English has been changed compared to what we have right now in production (see screenshots). Is this intended?

actual
pr

**Comment by Tazaria** [comment]
Yes that's intended. In the deployed version I rewrote level 8 with the idea in mind users would first go through a sublevel, but that is usually not the case so level 8 makes no sense in that version. That is why I rewrote it

**Comment by fpereiro** [comment]
Understood @Tazaria . Merging now!

**Review by fpereiro — APPROVED** [review]

**Pull request merged**
