### PR TITLE
Fixes Issue 1142: space at beginning of line gives error levels 3, 4, 5 and 6 

### PR DESCRIPTION
**Pull request by racertop**
**Description**
Fixes issue #1142, adding `invalid_space` rule to the grammars of those levels. I edited:

* grammars/level4-Additions.lark
* grammars/level4-Additions.lark
* grammars/level6-Additions.lark

To add  `invalid_space` as a rule in the `command` rule of those levels so it can appear later in the tree to be detected and fixed, just as we do in levels 1 and 2.

**Fix for**
#1142 

**How to test**

Just add a space to the beginning of a line in levels 3, 4, 5 and 6. 

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] Links to an existing issue or discussion (if not, create an issue first)
- [ ] Describes changes clear in the format above (present tense, no subject)
- [ ] Has a "how to test" section
- [ ] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by racertop** [comment]
Well, this fix might not work because spaces aren't allowed inside ifs in level 4+.

**Comment by Felienne** [comment]
> Well, this fix might not work because spaces aren't allowed inside ifs in level 4+.

Ah yeah true! We could allow them at the start of the line like we do with " print 'hallo'"? But I can also see how we only offer this sort of help until level 3.

**Comment by Felienne** [comment]
ok your error message is not bad:

image

But because this is legal code later on, it is a bit confusing. 

I think my preferred solution for level 5 (and 6, until we have indented blocks) is to allow this and give no warning at all. This might be done by kids (or parents) with a bit of programming knowledge already. What do you think?

**Comment by racertop** [comment]
@Felienne  I do agree this might be executable code. What about adding a new error message? Something like `InvalidMultilineIf`, that tells you "Your trying to write a multiline if, but that is not unlocked until later on", like we do with nested blocks in level 6, 7, etc. I'm not entirely sure how to achieve this, but Ill look into it.

**Comment by Felienne** [comment]
> @Felienne I do agree this might be executable code. What about adding a new error message? Something like `InvalidMultilineIf`, that tells you "You're trying to write a multiline if, but that is not unlocked until later on", like we do with nested blocks in level 6, 7, etc. I'm not entirely sure how to achieve this, but Ill look into it.

That is a lovely idea!! You can do that by throwing a LockedFeature Exception, see how that is done for example here: https://github.com/Felienne/hedy/blob/ba6c6ec1b32d100f8cc5ee88964c0ee9dfcc28e8/hedy.py#L1492

**Comment by Felienne** [comment]
Beware though, I am going to merge #1144 soon so you might want to wait a bit to avoid merge conflicts

**Comment by racertop** [comment]
> Beware though, I am going to merge #1144 soon so you might want to wait a bit to avoid merge conflicts

Perfect! I'm probably not going to work on this until the next few days, so I will pull before working on this new idea!

**Comment by Felienne** [comment]
Making this into draft so I can keep track of open pr's a bit easier

**Comment by Felienne** [comment]
Hi @racertop! What do you think about this one? Is there a path to finishing or is it too far behind main?

**Comment by racertop** [comment]
> Hi @racertop! What do you think about this one? Is there a path to finishing or is it too far behind main?

I think I'm going to do a new PR, since I have to redo some work. There is some more work before this is valid:

- Add a way to detect indented ifs on levels 4, 5, 6 (I have a working prototype for this but involves string hacking and I need to include your start block update).
- Add invalid_space rule to levels 4, 5, 6 (what this PR tries to do).

But maybe we can do better by adding an identer class to Hedy, which is what Im working on right now. It is compatible with the Earley parser if we use the standard lexer, I need to check if it doesn't mess to much with the grammar.


So I'm clossing this PR, I honestly should not have uploaded it before running tests locally, I'm sorry for that!

**Pull request closed without merging**
