### PR TITLE
[UI] Add searching to the ACE editor

### LINKED ISSUE #3342: [BUG] Can we enable search in Ace?
**Describe the bug**
Ace does not support search in Hedy at the moment, so if you hit ctrl-f nothing happens. Which is annoying in a long program

Can we enable it?

Maybe this will help: https://stackoverflow.com/questions/66681593/how-can-i-enable-the-search-box-in-an-ace-editor.

-------

Just a note for people also suffering from this until it is fixed: the browser can search, so if you click outside Ace, hitting ctrl-f does work:

image

### PR DESCRIPTION
**Pull request by ToniSkulj**
Enables searching in the ACE editor.

Fixes #3342 

**How to test**
Make sure to click the ACE editor and use the **ctrl+f** shortcut. This should open up the search bar. 
You can now search your code!

image

### CODE REVIEW

**Review by Felienne — APPROVED** [review]
Great!!! The "found color" is not super clear but I guess we can fix that separately

image

**Comment by TiBiBa** [comment]
> Great!!! The "found color" is not super clear but I guess we can fix that separately
> 
> image

To add on this it might be nice to also introduce some styling to the search box so the style aligns better with the rest of the site. As well as, for example, making the "All" string a babel placeholder. Shouldn't be to hard as we have the local .js file for the extension (and don't dependent on any CDN).

**Comment by ToniSkulj** [comment]
Great ideas! Maybe this is a solution @Felienne & @TiBiBa , the searchbox **selects** the word or sentence, I changed the selection color to the blue color that is being used throughout the website. This will make selection also more visible I guess. I also made the searchbox look like the ACE Monokai theme.

_Search_
image

_Select_
image


Let me know what you think!

**Comment by Felienne** [comment]
> Great ideas! Maybe this is a solution @Felienne & @TiBiBa , the searchbox **selects** the word or sentence, I changed the selection color to the blue color that is being used throughout the website. This will make selection also more visible I guess. I also made the searchbox look like the ACE Monokai theme.
> 
> _Search_ image
> 
> _Select_ image
> 
> Let me know what you think!

Looks great!! Can you make a PR for this?

**Comment by ToniSkulj** [comment]
> Looks great!! Can you make a PR for this?

I sure can! Related PR: #3504

**Pull request merged**
