### PR TITLE
delete main folder and move menu.json to home directory

### PR DESCRIPTION
**Pull request by rahulchandra17**
Provide a general summary of your changes in the Title of the PR

**Description**

Describe your changes in detail. Please use present tense without a subject to describe your PR, for example: "Fix**es** issue 123" or "Adds translations of levels 1 to 12 for Polish"

**Fix for**

Describe what issue or discussion your pr concerns

**How to test**

Describe how to run your code to see it is action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example.

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] Links to an existing issue or discussion (if not, create an issue first)
- [ ] Describes changes clear in the format above (present tense, no subject)
- [ ] Has a "how to test" section
- [ ] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by rahulchandra17** [comment]
make a pull request please review it

**Comment by Felienne** [comment]
Thanks @rahulchandra17!

This is a good start but in some locations in the code we refer to the menu with `main/menu.json` (f.e. in app.py on line 158) there will also need to be updated.

You can see the failing tests in the build here: https://github.com/Felienne/hedy/runs/4416687921?check_suite_focus=true

**Comment by rahulchandra17** [comment]
Okk I update it

**Comment by rahulchandra17** [comment]
i update it please review

**Comment by rahulchandra17** [comment]
Thanks for help

**Comment by Felienne** [comment]
> Thanks for help

Thanks for your first Hedy contribution! Let us know if you want to pick up other issues too!!

**Comment by rahulchandra17** [comment]
Please merge my pull request

**Comment by Felienne** [comment]
Closes #1459

**Review by Felienne — APPROVED** [review]

**Comment by Felienne** [comment]
> Please merge my pull request

Yeah I did but the tests take about 6 mins to complete :D Is merged now!

**Pull request merged**
