### PR TITLE
[UI improvement] Clean-up and improve menu bar

### LINKED ISSUE #1149: [UI idea] Make logout button accesible from every page
**Idea incl level**
Currently there is a "login" button in the menubar, being accessible for every page on the website. However, when logged in this button is replaced by the "my programs" button. To logout we have to navigate to "my profile" and then use the logout button. I propose to implement a logout button within the menu-bar, making it clearly visible to the user.   I create a simple mock-up as example, which can be found in the screenshots below. However, it might be nice to do some menubar styling together with this button implementation.

**Additional context: Proposed new UI design**
Schermafbeelding 2021-11-02 om 19 45 43
Schermafbeelding 2021-11-02 om 19 45 54

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
Currently the menubar can feel "crowded" with the overload of options. In this PR we built upon the work done in #1466 and clean-up and improve the menubar. A logout icon is implemented which enables users to logout from every page. Which, together with the profile settings and for-teachers page is placed under a dropdown menu of the user. We also add a `:hover` to all menubar elements to give more feedback to the user. The language selector dropdown is re-styled to better aligned with rest of UI. In future work the language selector should be removed when a user is logged in.

**Fix for**
This PR fixed #1149.

**Old view**
Schermafbeelding 2021-12-07 om 11 23 35

**New view**
Schermafbeelding 2021-12-07 om 11 22 49
Schermafbeelding 2021-12-07 om 11 23 58

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] Links to an existing issue or discussion (if not, create an issue first)
- [ ] Describes changes clear in the format above (present tense, no subject)
- [ ] Has a "how to test" section
- [ ] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by TiBiBa** [comment]
Current state of progress:

**Old view**
Schermafbeelding 2021-12-06 om 13 12 15

**New view**
Schermafbeelding 2021-12-06 om 13 12 00

**Comment by rix0rrr** [comment]
If we have a dropdown anyway, should "logout" not more properly be part of the dropdown as well? That's how most other sites do it at least.

**Comment by TiBiBa** [comment]
> If we have a dropdown anyway, should "logout" not more properly be part of the dropdown as well? That's how most other sites do it at least.

Agree! Will change this.

**Comment by TiBiBa** [comment]
> Btw, you're saying that a user has a language which is automatically honored... can you point me to where that's implemented?

Sorry, I wrote it down wrong; the goal is to implement this within user settings. Together with re-styling the profile page. This because I assume once a user is there they won't switch languages alot, making the language dropdown in the menubar a bit unneccesary. If they really want they can always change it in their settings.

**Comment by Felienne** [comment]
> **Fix for**
> This PR fixed #1149.

yeah that is a good idea because I did not understand the exit symbol haha

**Comment by Felienne** [comment]
> > If we have a dropdown anyway, should "logout" not more properly be part of the dropdown as well? That's how most other sites do it at least.
> 
> Agree! Will change this.

yeah that is a good idea because I did not understand the exit symbol haha

**Comment by Felienne** [comment]
> > Btw, you're saying that a user has a language which is automatically honored... can you point me to where that's implemented?
> 
> Sorry, I wrote it down wrong; the goal is to implement this within user settings. Together with re-styling the profile page. This because I assume once a user is there they won't switch languages alot, making the language dropdown in the menubar a bit unneccesary. If they really want they can always change it in their settings.

Shouldn't we implement that first (or in this PR?) because now I have lost the switcher and I have no way to switch but manipulate the url (which is not great for demos for me), but also kids will not know how to get to Dutch?

**Comment by TiBiBa** [comment]
> > > Btw, you're saying that a user has a language which is automatically honored... can you point me to where that's implemented?
> > 
> > 
> > Sorry, I wrote it down wrong; the goal is to implement this within user settings. Together with re-styling the profile page. This because I assume once a user is there they won't switch languages alot, making the language dropdown in the menubar a bit unneccesary. If they really want they can always change it in their settings.
> 
> Shouldn't we implement that first (or in this PR?) because now I have lost the switcher and I have no way to switch but manipulate the url (which is not great for demos for me), but also kids will not know how to get to Dutch?

Will fix this in this PR. We have to think about how we set the initial value for users (automatically at Dutch?) We also have to make clear that they can change languages on the profile settings. Will think about a feasible solution and commit it within this PR.

**Comment by TiBiBa** [comment]
> > > Btw, you're saying that a user has a language which is automatically honored... can you point me to where that's implemented?
> > 
> > 
> > Sorry, I wrote it down wrong; the goal is to implement this within user settings. Together with re-styling the profile page. This because I assume once a user is there they won't switch languages alot, making the language dropdown in the menubar a bit unneccesary. If they really want they can always change it in their settings.
> 
> Shouldn't we implement that first (or in this PR?) because now I have lost the switcher and I have no way to switch but manipulate the url (which is not great for demos for me), but also kids will not know how to get to Dutch?

On seconds thought, I think it would be best to do this in a different issue and PR as it is quite some work to implement (we also have to make some back-end db changes). Will make the language selector always show for now so we can merge this PR.

**Comment by Felienne** [comment]
Ah sorry this now as an issue and I am not sure how to fix it, can you do that @TiBiBa?

**Comment by TiBiBa** [comment]
> Ah sorry this now has an issue and I am not sure how to fix it, can you do that @TiBiBa?

Seem to be some issues with the last fix with the lang argument. Will take a look!

**Comment by TiBiBa** [comment]
I think it should all be fixed and ready to merge!

**Review by Felienne — APPROVED** [review]
Looks great @TiBiBa!!

**Pull request merged**
