### PR TITLE
repair quote usage coursedata

### LINKED ISSUE #2129: [CONTENT] missing quotation marks in story level 5
Level 5 story

Line 1 and line 4 are missing quotation marks, turning `is ask` into `is` + str, which leads to an incorrect execution of the code.

Furthermore, the syntax highlighting interprets this as `is ask` without quotes, which can mislead children

image

### LINKED ISSUE #2189: [BUG]
French examples use strange dot, which also gets highlighted:

image

(level 1)

Do you know what't up here @thjazi39?

### PR DESCRIPTION
**Pull request by thjazi39**
fix #2129 
There was some misuse of quotes in the adventures, level-data, and quiz files.
UPDATE : 

fix #2189
(strange space)

### CODE REVIEW

**Comment by thjazi39** [comment]
I found at least 9 errors of the same type in the files quizzes/fr.yaml and level-defaut/fr.yaml
But I don't know if it's better to do this on this branch, or if I should do another PR

**Review by Felienne — DISMISSED** [review]

**Comment by Felienne** [comment]
> I found at least 9 errors of the same type in the files quizzes/fr.yaml and level-defaut/fr.yaml But I don't know if it's better to do this on this branch, or if I should do another PR

Let's do that in this PR too!

**Comment by thjazi39** [comment]
fix #2189 
(strange space)

**Comment by thjazi39** [comment]
I also looked at the use of quotes in Dutch files, but I think I'll stop here (I'm afraid to have conflicts with the yaml from the translation site)

**Comment by thjazi39** [comment]
I found this :
```
{'language': 'nl', 'level': 7, 'question': 1, 'answer': 'In this level you can only repeat one line at a time'}
{'language': 'nl', 'level': 7, 'question': 3, 'answer': 'The word repeat is there, another word is missing'}
{'language': 'nl', 'level': 7, 'question': 5, 'answer': "That's not it"}
{'language': 'nl', 'level': 8, 'question': 8, 'answer': ''}
```
with a little script that is supposed to select only the right answers, but I guess they are not positive answers.

I can correct these errors in this PR too if needed

**Review by Felienne — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
