### PR TITLE
Swahili translations 

### PR DESCRIPTION
**Pull request by Princekrampah**
Translations to swahili for UI and levels done. Main page translations left to be done.

### CODE REVIEW

**Comment by Princekrampah** [comment]
Swahili translations for all levels and UI components done

**Comment by Princekrampah** [comment]
Swahili translations done

**Comment by Felienne** [comment]
Thanks a lot for this @Princekrampah!!! There were a few issues in the code (you missed a few comma's) but I fixed those for you.

**Review by Felienne — APPROVED** [review]

**Comment by Princekrampah** [comment]
Awesome, thanks!

**Comment by Princekrampah** [comment]
I'll keep improving the translation. Thanks alot. Can you please provide me
with the resources needed to understand how you went about building the
Hedy Language. Thanks

Best regards,
Prince

**Pull request merged**
