### PR TITLE
Re-structure tutorials to support level-based structure

### LINKED ISSUE #3163: [UI idea] Implement level tutorial template
**Idea incl level**
It would be nice if we have a template in place to enable us to easily create a tutorial for each level. At this point we only have one general tutorial but it would be nice to built onto this.

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we re-structure the tutorial front-end code to make it easier to add new tutorials (and specifically levels) later on. We split the tutorial file intro two main parts:
- `tutorial.ts`
- `utils.ts`

`tutorial.ts` is the "aanspreekpunt" from the front-end, handling the requests for the specific tutorial and make sure that some values and onclick attributes are set correctly. `utils.py` contains some handy functions that can be used by the specific tutorials. Such as highlighting a specific part of the page or adding a border. It also contains the functionality to make a POST against the server and retrieve the next step. This is then all handled automatically.

Lastly, for each specific tutorial a new file has to be added. Currently there are already three files:
- `intro.ts`
- `teacher.ts`
- `level1.ts`

The first two files contain the code for the two already existing tutorials and can be used as inspiration on how to handle new tutorials with new steps. The `level1.ts` is a template file and currently empty. This should help contributors by adding new tutorials.

**Fixes**
This PR fixes #3163.

**How to test**
This is merely a re-structuring, no new content or functionality is added. Verify that both the normal tutorial and the teacher tutorial still work as expected, than this can be merged.

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @TiBiBa!

If this is just a restructuring I think it does not yet close #3163, but is just a preparation?

**Comment by Felienne** [comment]
(otherwise everything still works!)

**Comment by TiBiBa** [comment]
This does the re-structuring as of #3163. The actual tutorials are a separate issue, #2777. However, with this PR it should be feasible for all contributors to create a tutorial level.

**Comment by Felienne** [comment]
> This does the re-structuring as of #3163. The actual tutorials are a separate issue, #2777. However, with this PR it should be feasible for all contributors to create a tutorial level.

Ah got it! Shall I try to create one this week to see if I know how to?

**Review by Felienne — APPROVED** [review]

**Pull request merged**
