### PR TITLE
Level 14 and 15 

### PR DESCRIPTION
**Pull request by LauraTSD**
Tests, text, grammar file for levels 14 and 15

### CODE REVIEW

**Comment by Felienne** [comment]
Great job @LauraTSD! One small request, can you update our level docs also (here: https://github.com/Felienne/hedy/blob/master/DESIGN.md) so we are up to date?

**Review by Felienne — CHANGES_REQUESTED** [review]
Can you update the design docs also? https://github.com/Felienne/hedy/blob/master/DESIGN.md

**Comment by fpereiro** [comment]
Congrats on two more levels @LauraTSD !

One little request: could you add entries for levels 14 and 15 in DESIGN.md?

**Review by fpereiro — APPROVED** [review]

**Comment by LauraTSD** [comment]
After conversation with Felienne, closing this pr due to reordering of the levels

**Pull request closed without merging**
