### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Hedy/Adventures](https://hosted.weblate.org/projects/hedy/adventures/).

It also includes following components:

* [Hedy/Quizzes](https://hosted.weblate.org/projects/hedy/quizzes/)

* [Hedy/Achievements](https://hosted.weblate.org/projects/hedy/achievements/)

* [Hedy/Texts](https://hosted.weblate.org/projects/hedy/web-texts/)

* [Hedy/Commands](https://hosted.weblate.org/projects/hedy/commands/)

* [Hedy/client-messages](https://hosted.weblate.org/projects/hedy/client-messages/)

* [Hedy/Webpages](https://hosted.weblate.org/projects/hedy/webpages/)

* [Hedy/Keywords](https://hosted.weblate.org/projects/hedy/keywords/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Mark-Giesen** [comment]
Leave this one for now. This is an empty one again, I'd like to have Weblate take a look at this.

**Comment by Felienne** [comment]
Cooooool, (partly) Arabic error messages:

image

Thanks a bunch @nalmadi!!

**Comment by Felienne** [comment]
@Mark-Giesen Do we want to merge this now to prevent conflicts later, or leave it open because it started out with the empty changes again (which will likely come back after merging)

**Comment by Mark-Giesen** [comment]
We can merge it

**Review by Felienne — APPROVED** [review]

**Pull request merged**
