### PR TITLE
[FEATURE] Adds 'agree to terms' tickmark to sign-up page

### LINKED ISSUE #2023: [UI addition] Agree to third party info on signup
Since we are finalising our agreement with Lyceo, we need to add a tickmark to account signup where people agree that they might be contacted by third parties we work with. We need to save this consent in the database we so can share only the information of people that agree with Lyceo.

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we perform an overall UI re-style of the signup page and implement an additional tick mark for agreeing with the privacy agreement. Real-time form validation is implementation using the CSS `input:valid` attribute. A very small re-write is performed in auth.py to better differentiate between functionality within functions and make clear where the mailinglist and teacher account filtering is done.

**Fix for**
This PR fixes #2023 

**How to test**
Navigate to the signup page and notice the new UI and the new tickmark at the bottom of the page. Verify that the tickmark is not required and (when not in testing) an e-mail is sent to the admin when the tickmarked is checked on signup.

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] Links to an existing issue or discussion (if not, create an issue first)
- [ ] Describes changes clear in the format above (present tense, no subject)
- [ ] Has a "how to test" section
- [ ] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by TiBiBa** [comment]
**Old UI**
Schermafbeelding 2022-02-18 om 11 37 47

**New UI**
Schermafbeelding 2022-02-18 om 11 36 44

**Comment by Felienne** [comment]
Hi @TiBiBa! When the fix the conflicts, I think the is almost ready, apart from these two things:

1) I think this should be checkmarks and not radiobuttons? The are not mutually exclusive. 
image

2) We need the privacy terms to be a link to a text file (markdown I think is easiest?) that people can click, maybe as a modal popup? If you make an md file filled with "privacy terms" or another place holder, I will push the text.

**Comment by TiBiBa** [comment]
> Hi @TiBiBa! When the fix the conflicts, I think the is almost ready, apart from these two things:
> 
> 1. I think this should be checkmarks and not radiobuttons? The are not mutually exclusive.
> 
> image
> 
> 2. We need the privacy terms to be a link to a text file (markdown I think is easiest?) that people can click, maybe as a modal popup? If you make an md file filled with "privacy terms" or another place holder, I will push the text.

Will fix both today, a modal pop sounds like a nice solution!

**Comment by TiBiBa** [comment]
Both are fixed! Funny sidenote: these where already checkboxes, but due to the styling they looked a bit too much a-like to the radio buttons. Changed the styling a bit so they are square again to clearly differentiate between both options. For the agreement itself we use the same structure as for all other "general purpose" site translations:

In the folder `/coursedata/pages/privacy` there are currently two yaml placeholders for English and Dutch. These can be adjusted to contain the actual privacy agreement (and more languages can be added).

**Review by Felienne — APPROVED** [review]

**Comment by Felienne** [comment]
Ah some merge conflicts @TiBiBa :( Can you have a peak? Otherwise we are good to go I think!

**Comment by TiBiBa** [comment]
> Ah some merge conflicts @TiBiBa :( Can you have a peak? Otherwise we are good to go I think!

Will take a look!

**Comment by TiBiBa** [comment]
I think we only have to fix some e2e tests and we're ready

**Review by Felienne — APPROVED** [review]

**Pull request merged**
