### PR TITLE
Change program translation so that it preserves all tokens lost during parsing #2114

### PR DESCRIPTION
**Pull request by boryanagoncharenko**
**Please fill out this template by replacing all content between < >**

< Change program translation mechanism >

**Description**

Instead of parsing and then reconstructing the tree, we now translate programs through extracting tokens' meta information from the parse tree and replacing them in the original user input string with their translated counterparts.

** IMPORTANT NOTE **

Note that this PR contains 3 changes of tests which seem rather weird: 
1) https://github.com/Felienne/hedy/pull/2115/files#diff-f558aa077eea06d131071ab6183c4fccd65dfd56f6974e5e9bce489009a62003R196-R197
2) https://github.com/Felienne/hedy/pull/2115/files#diff-f558aa077eea06d131071ab6183c4fccd65dfd56f6974e5e9bce489009a62003R243-R244
3) https://github.com/Felienne/hedy/pull/2115/files#diff-3f91877484ae8f3c806b4ecad51415810d8cf160f6839037264cffd8e48cabd7R407-R408

After preserving the whitespaces, these tests started failing intermittently. The reason seems to be that when we do not preserve whitespacing, the command following the 'else' clause was put on the same line as the else itself (see the last line):
```
people is mom, dad, Emma, Sophie
dishwasher is people op willekeurig
als dishwasher is Sophie
print \'too bad I have to do the dishes\'
anders print 'luckily no dishes because' dishwasher 'is already washing up'
```

However, now, the same code is translated to the following. Note that the print command is on the next line of 'anders'
```
people is mom, dad, Emma, Sophie
dishwasher is people op willekeurig
als dishwasher is Sophie
print \'too bad I have to do the dishes\'
anders
print 'luckily no dishes because' dishwasher 'is already washing up'
```

Apparently there is ambiguity in the grammar which exists regardless of the changes in the current PR. I can replicate the issue by adding the following test to the test_translation_level_05.py of the main branch. Please note that sometimes I have to run it 10 times before it fails. Created issue #2116 to trans this problem.
```
    def test_fail(self):
        code = textwrap.dedent("""\
            people is mom, dad, Emma, Sophie
            dishwasher is people op willekeurig
            als dishwasher is Sophie
            print 'too bad I have to do the dishes'
            anders
            print 'luckily no dishes because' dishwasher 'is already washing up'""")

        result = hedy_translation.translate_keywords(code, from_lang="nl", to_lang="en", level=self.level)
        expected = textwrap.dedent("""\
            people is mom, dad, Emma, Sophie
            dishwasher is people at random
            if dishwasher is Sophie
            print 'too bad I have to do the dishes'
            else print 'luckily no dishes because' dishwasher 'is already washing up'""")

        self.assertEqual(expected, result)
```

I created a new issue describing just that problematic test: 

**Fixes < #2114  >**

< Always link the number of the issue or of the discussion that your pr concerns. >
Notable exception: adding content may be done without an accompanying issue 

**How to test**

- All tests should pass
- You could perform manual tests of translating a program back and forth. Note that whitespacing is preserved now. 

**Checklist**
Done? Check if you have it all in place using this list*
  
- [x] Describes changes in the format above (present tense)
- [x] Links to an existing issue or discussion 
- [x] Has a "How to test" section

* If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by Felienne** [comment]
Great work @boryanagoncharenko!! I will see if all still works but it looks promising. And I think I know exactly what is up with that one test, so I will pick that up!

**Comment by Felienne** [comment]
Sorry @jpelay this improves but almost destroys your hard work on the translation preservation (#1587) Guess @boryanagoncharenko outsmarts us both with her in-depth Lark understanding 🤣!

But the work was not entirely reversed; the separate rules for input remain, so it was not all for nothing!

**Comment by Felienne** [comment]
@boryanagoncharenko, I removed some duplicate rules that we only had in the grammar so we could preserve some token, so now the grammar is even simpler (that's really nice!)

**Review by Felienne — APPROVED** [review]

**Comment by jpelay** [comment]
> Sorry @jpelay this improves but almost destroys your hard work on the translation preservation (#1587) Guess @boryanagoncharenko outsmarts us both with her in-depth Lark understanding 🤣!
> 
> But the work was not entirely reversed; the separate rules for input remain, so it was not all for nothing!

But this is a great change :) Makes things a lot better!!

**Comment by Felienne** [comment]
> > Sorry @jpelay this improves but almost destroys your hard work on the translation preservation (#1587) Guess @boryanagoncharenko outsmarts us both with her in-depth Lark understanding 🤣!
> > But the work was not entirely reversed; the separate rules for input remain, so it was not all for nothing!
> 
> But this is a great change :) Makes things a lot better!!

Thanks for being so understanding! And yeah I do think it is nicer without duplication of the rules

**Pull request merged**
