### PR TITLE
adding my master thesis to the semantics folder

### PR DESCRIPTION
**Pull request by juliabolt**
**Description**

Adds my master thesis called "An approach to describing the semantics of Hedy" to the repo, in the semantics folder.

**Fixes _issue or discussion number_ not applicable**

**How to test**
 read my thesis? haha

**Checklist**
Done? Check if you have it all in place using this list:*
  
- [ ] Describes changes in the format above (present tense)
- [ ] Links to an existing issue or discussion 
- [ ] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by TiBiBa** [comment]
Nice! It might be nice to add all related Hedy research to the website as well. Maybe we can add a section on the learn-more page with "Hedy research"? Because a .pdf without routing is not accessible by users.

**Comment by TiBiBa** [comment]
Will look into this later today before we merge this PR, then we can store all research related files in a dedicated folder and add the routing.

**Comment by TiBiBa** [comment]
Sorry @juliabolt, completely forgot about this one. Will look into this today to nicely add a section to the learn-more page!

**Comment by TiBiBa** [comment]
Hi @juliabolt! I just created a new PR where we dynamically load the .pdf files in the research folder and show them on the learn-more page. Can you take a look? #3038. For some reason I can't select you as a reviewer! I've already added your thesis as an example.

**Comment by Felienne** [comment]
Superseded by #3038

**Pull request closed without merging**
