### PR TITLE
Structure for translation level 3-5 + tests

### PR DESCRIPTION
**Pull request by emil-meyknecht**
Added level 3 to 5 into the translation structure.

-Adds level 3,4 and 5 to the translation structure
-Adds tests for translation of levels 3,4 and 5
-Adds support for lists, if statements and strings in quotes

Tests available by running the tests

### CODE REVIEW

**Comment by teundemast** [comment]
I wouldn't define the function check_local_bool in every file, but define it in one file and import in the others. I've already implemented this approach in PR #1424

**Comment by Felienne** [comment]
> I wouldn't define the function check_local_bool in every file, but define it in one file and import in the others. I've already implemented this approach in PR #1424

Does this mean a change if needed here @teundemast, or are you ok with it like this (I am ok as it is)

**Comment by emil-meyknecht** [comment]
I will add the change to this branch @teundemast @Felienne

**Comment by Felienne** [comment]
> I will add the change to this branch @teundemast @Felienne

ok!

**Comment by emil-meyknecht** [comment]
@Felienne The decorator has now been moved to the test_translating.py file. But if you prefer we can move it to the Tester.py file.

**Comment by emil-meyknecht** [comment]
@Felienne Is there anything else we should add?

**Review by Felienne — APPROVED** [review]

**Comment by Felienne** [comment]
> @Felienne Is there anything else we should add?

Nope, looks good!

**Pull request merged**
