### PR TITLE
[BUG FIX] explore page no longer crashes when filtering

### LINKED ISSUE #1862: [BUG] Explore crashes when filtering without being logged in
**Describe the bug**
Currently the /explore page crashes if you try to filter without being logged in. This is due to the achievements being added without verifying if there is a user. 

**Expected behavior**
Anyone can filter on the /explore page, without being logged in.

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we fix an issue where the page would crash when filtering without being logged in.

**Fix for**
This PR fixes #1862

**How to test**
Make sure you're logged out and verify you can filter on the /explore page

### CODE REVIEW

**Comment by Felienne** [comment]
Didn't we allow exploring only when logged in anyway?

image

**Comment by TiBiBa** [comment]
> Didn't we allow exploring only when logged in anyway?
> 
> image

I just noticed this as well! But when looking at the code I have no indication that we restrict /explore to logged in users. So not sure why this view is shown.

**Comment by Felienne** [comment]
Haha ok, but it is the way I wanted it :D

**Comment by Felienne** [comment]
Ah I see, this is true for hedycode but not for main/alpha. So it figures you did not find it in the code, because it is no longer there. But can we put it back, that seems to be the real issue.

**Review by ThomasKluiters — APPROVED** [review]

**Review by ThomasKluiters — APPROVED** [review]

**Pull request merged**
