### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Hedy/Adventures](https://hosted.weblate.org/projects/hedy/adventures/).

It also includes following components:

* [Hedy/Quizzes](https://hosted.weblate.org/projects/hedy/quizzes/)

* [Hedy/Parsons](https://hosted.weblate.org/projects/hedy/parsons/)

* [Hedy/Achievements](https://hosted.weblate.org/projects/hedy/achievements/)

* [Hedy/Webpages](https://hosted.weblate.org/projects/hedy/webpages/)

* [Hedy/Commands](https://hosted.weblate.org/projects/hedy/commands/)

* [Hedy/client-messages](https://hosted.weblate.org/projects/hedy/client-messages/)

* [Hedy/Texts](https://hosted.weblate.org/projects/hedy/web-texts/)

* [Hedy/Keywords](https://hosted.weblate.org/projects/hedy/keywords/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Felienne** [comment]
@TiBiBa 😭 Can you take a look at the conflicts?

**Comment by TiBiBa** [comment]
> @TiBiBa 😭 Can you take a look at the conflicts?

Will do! We will also have to add a new component for the tutorial YAMLs. I'm not really familiar with Weblate, do you know how we can fix this?

**Comment by Felienne** [comment]
> > @TiBiBa 😭 Can you take a look at the conflicts?
> 
> Will do! We will also have to add a new component for the tutorial YAMLs. I'm not really familiar with Weblate, do you know how we can fix this?

No but @Mark-Giesen will know I guess (or he can show me next week)

**Comment by TiBiBa** [comment]
These conflicts are quite complex, will have to merge these manually (and will take some time). Will look into this today.

**Comment by Felienne** [comment]
> These conflicts are quite complex, will have to merge these manually (and will take some time). Will look into this today.

np I am picking them up now (it was an issue I introduced with the new exception)

**Pull request merged**
