### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Hedy/Level defaults](https://hosted.weblate.org/projects/hedy/level-defaults/).

It also includes following components:

* [Hedy/web-learn more](https://hosted.weblate.org/projects/hedy/web-learn-more/)

* [Hedy/web-For teachers](https://hosted.weblate.org/projects/hedy/web-for-teachers/)

* [Hedy/Keywords](https://hosted.weblate.org/projects/hedy/keywords/)

* [Hedy/web-Start](https://hosted.weblate.org/projects/hedy/web-start/)

* [Hedy/emails](https://hosted.weblate.org/projects/hedy/emails/)

* [Hedy/client-messages](https://hosted.weblate.org/projects/hedy/client-messages/)

* [Hedy/Commands](https://hosted.weblate.org/projects/hedy/commands/)

* [Hedy/Achievements](https://hosted.weblate.org/projects/hedy/achievements/)

* [Hedy/Quizzes](https://hosted.weblate.org/projects/hedy/quizzes/)

* [Hedy/Adventures](https://hosted.weblate.org/projects/hedy/adventures/)

* [Hedy/web-texts](https://hosted.weblate.org/projects/hedy/web-texts/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by TiBiBa — COMMENTED** [review]
Weblate seems to remove all headers, but not sure if that is the desired behavior. As stated by @Mark-Giesen it might introduce issues with non-ASCII files?

**Comment by Mark-Giesen** [comment]
> Weblate seems to remove all headers, but not sure if that is the desired behavior. As stated by @Mark-Giesen it might introduce issues with non-ASCII files?

That was a experiment, the documentation of Weblate suggested it would skip the "team-header". Not sure which part that was, now we know. Reverted the change. A sollutions using the .pot file might be a better way to keep repo's clean and in sync.

**Comment by Felienne** [comment]
> > Weblate seems to remove all headers, but not sure if that is the desired behavior. As stated by @Mark-Giesen it might introduce issues with non-ASCII files?
> 
> That was a experiment, the documentation of Weblate suggested it would skip the "team-header". Not sure which part that was, now we know. Reverted the change. A sollutions using the .pot file might be a better way to keep repo's clean and in sync.

Where does that leave this PR? Should we merge or close it?

**Review by Mark-Giesen — APPROVED** [review]

**Comment by Mark-Giesen** [comment]
Header seems to be extended by weblate. maybe adding the .pot file there will solve this. We'll try next.

**Pull request merged**
