### PR TITLE
Update lark to latest 1.1.1

### PR DESCRIPTION
**Pull request by bjorn3**
This updates lark to the latest version. None of the breaking changes affect hedy AFAICT. All tests pass. I think you need to do `pip uninstall lark-parser; pip install -r requirements.txt` when updating locally due to the package having been renamed.

Part of #1312

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks for this @bjorn3, but we are now in a bit too much churn with too many people working on Hedy daily for this to be smart now. Will do this over Christmas.

**Comment by Felienne** [comment]
Hi @boryanagoncharenko!

I think since we are in a state to start improving things, maybe we can follow through on this one now? Once we do this (quite easy, just update this and see all tests still work) we could improve/simplify the code A LOT by using grammar compositions instead of our own grammar merging (https://github.com/Felienne/hedy/issues/1312)

**Comment by Felienne** [comment]
Ah it seems they changed things wrt meta so we will need to make at least some changes to make this work (if absolutely needed we could drop meta since it is not actively used now)

**Comment by boryanagoncharenko** [comment]
> Ah it seems they changed things wrt meta so we will need to make at least some changes to make this work (if absolutely needed we could drop meta since it is not actively used now)

Merged and resolved the latest changes without removing the meta information for now.

**Comment by Felienne** [comment]
> This updates lark to the latest version. None of the breaking changes affect hedy AFAICT. All tests pass. I think you need to do `pip uninstall lark-parser; pip install -r requirements.txt` when updating locally due to the package having been renamed.

For me, `pip uninstall lark-parser; pip install -r requirements.txt` did not work, but `pip uninstall lark; pip install -r requirements.txt` did the trick. Maybe I had both installed?

**Review by Felienne — APPROVED** [review]

**Pull request merged**
