### PR TITLE
Implement landing page

### LINKED ISSUE #722: Better landing page for new accounts (also for new teachers)
Just registered a new account on GitHub and this is just amazing:

image

I want something like that!!

For students is should be one or two adventures (like we had way back when with the adventure page) 
For teachers it should be:
* Try Hedy
* Make a class
* Read teacher's material

### LINKED ISSUE #981: Implement landing page when verifying mail address
Currently when verifying your mail address after creating an account you land on the homepage; giving the user no information if the verification of the mail address was successful. It would be nice to return the user with some additional information such as "your account is successful verified". We can implement this by creating an additional "landing" page when clicking the verify link in the mail with (maybe) an automatic re-direct to the homepage after x seconds.

### PR DESCRIPTION
**Pull request by TiBiBa**
Provide a general summary of your changes in the Title of the PR

**Description**
Currently when a user creates an account they receive an e-mail to verify this account. After clicking this link they automatically re-direct to the main page. In this PR we implement a landing page to which they are re-directing, containing some general information on the possibilities and features of the Hedy website.

**Fix for**
This PR fixed #722 and fixed #981.

**How to test**
Create a new account and click the verification link in the mail. Notice the landing page and the instructions on the different functionalities.

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] Links to an existing issue or discussion (if not, create an issue first)
- [ ] Describes changes clear in the format above (present tense, no subject)
- [ ] Has a "how to test" section
- [ ] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by TiBiBa** [comment]
Still a WiP, some changes have to be made to create a universal page for both the student and teacher landing page. We also still have to discuss the use of either .md files (as required by the /page function) or structure it with the *.yaml files.

**Comment by Felienne** [comment]
Thanks @TiBiBa! This was on our wish list for a long time! 

I added some links and drawings, but one thing that is a bit annoying the fact that we can't use newlines:

image

I would want "Kies hieronder" to start on a new line. Can we make that happen? (I tried obvious hacks like putting <br> in the yaml but that did not work.

**Comment by Felienne** [comment]
Ow and with a longer text the margin is a bit off:

image

**Review by Felienne — APPROVED** [review]
If possible, can we fix the margins and the newlines?

**Review by Felienne — CHANGES_REQUESTED** [review]
If possible, can we fix the margins and the newlines?

**Comment by TiBiBa** [comment]
> Thanks @TiBiBa! This was on our wish list for a long time! 
> 
> 
> 
> I added some links and drawings, but one thing that is a bit annoying the fact that we can't use newlines:
> 
> 
> 
> image
> 
> 
> 
> I would want "Kies hieronder" to start on a new line. Can we make that happen? (I tried obvious hacks like putting <br> in the yaml but that did not work)

I will take a look! I think we can achieve this with some Javascript tweaking, but I don't think that is the desirable way. Maybe split into two yaml keywords? Then we can store them in two <div> and do the styling within the HTML.

**Comment by TiBiBa** [comment]
Some small improvements to the margin, text centering, box background and border rounding:
Schermafbeelding 2021-11-26 om 15 47 10

**Comment by TiBiBa** [comment]
It might also be nice to "stick" the buttons at the bottom of the container so they are always aligned together. Currently they differ in height.

**Comment by Felienne** [comment]
@rix0rrr suggested to use markdown for the newlines (should have though of that myself!)

**Comment by Felienne** [comment]
> It might also be nice to "stick" the buttons at the bottom of the container so they are always aligned together. Currently they differ in height.

Ah yeah agreed (I did not even notice without you telling me they were not aligned) Do you plan to fix that still in this PR?

**Comment by TiBiBa** [comment]
> > It might also be nice to "stick" the buttons at the bottom of the container so they are always aligned together. Currently they differ in height.
> 
> 
> 
> Ah yeah agreed (I did not even notice without you telling me they were not aligned) Do you plan to fix that still in this PR?

Yes! Will fix this (think sunday) in this PR. If you plan to merge it before then I will just fix it with a different issue

**Comment by Felienne** [comment]
> > > It might also be nice to "stick" the buttons at the bottom of the container so they are always aligned together. Currently they differ in height.
> > 
> > 
> > Ah yeah agreed (I did not even notice without you telling me they were not aligned) Do you plan to fix that still in this PR?
> 
> Yes! Will fix this (think sunday) in this PR. If you plan to merge it before then I will just fix it with a different issue

Sunday is fine, not much kids "Hedy" in the weekend :D

**Comment by TiBiBa** [comment]
> > > > It might also be nice to "stick" the buttons at the bottom of the container so they are always aligned together. Currently they differ in height.
> > > 
> > > 
> > > Ah yeah agreed (I did not even notice without you telling me they were not aligned) Do you plan to fix that still in this PR?
> > 
> > 
> > Yes! Will fix this (think sunday) in this PR. If you plan to merge it before then I will just fix it with a different issue
> 
> Sunday is fine, not much kids "Hedy" in the weekend :D

Fixed the "stuck buttons to button of container"-issue! I think the PR is ready for merging now. (However, the unit tests seem to fail for some reason?)

**Comment by TiBiBa** [comment]
Not sure what has changed, it executed fine until 2 days ago and I think we only made front-end changes.

**Comment by Felienne** [comment]
> Not sure what has changed, it executed fine until 2 days ago and I think we only made front-end changes.

We also merged #1282, I think that might have caused this issue?

**Comment by Felienne** [comment]
Yeah, this is the issue, we test the redirect, which is now changed:

image

I can fix that for you, no problem!

**Review by Felienne — APPROVED** [review]

**Pull request merged**
