### PR TITLE
Fix #1283 Delaying confetti to end of execution

### LINKED ISSUE #1283: Delay confetti to end of execution
**Describe the bug**
When you create a program with ask, you immediately get the well done/confetti bar

**Add a screenshot (optional)**
For example in level 2:
image

**Expected behavior**
Can we make the confetti appear only when the program is done?

### PR DESCRIPTION
**Pull request by fRedelaar**
**Description**

Fix for issue #1283. The confetti emoji won't be shown until the program is over, so ask programs have to be filled in by the user.

https://user-images.githubusercontent.com/33595265/143560470-2d7c85f0-088f-4358-947a-1b0561623d94.mov

### CODE REVIEW

**Comment by fRedelaar** [comment]
I just noticed a bug with warnings (because it can run, it shows a green and yellow notification), so I converted the MR to a draft. Will fix it probably later today.

**Comment by TiBiBa** [comment]
A bit of topic: I just noticed that we are also getting compliments and the option to show confetti when viewing a shared program of another user. Is that expected behavior? Otherwise we should implement some check if we are currently in the code editor or just executing someone else's their code.

**Comment by Felienne** [comment]
> **Edit** In extend to this suggestion. What do we want to do if a user runs an example program? They didn't do any work so should they receive a compliment?

I think this is a good point, shall we make a separate issue for that?

**Comment by fRedelaar** [comment]
> A bit of topic: I just noticed that we are also getting compliments and the option to show confetti when viewing a shared program of another user. Is that expected behavior? Otherwise we should implement some check if we are currently in the code editor or just executing someone else's their code.
> 
> **Edit** In extend to this suggestion. What do we want to do if a user runs an example program? They didn't do any work so should they receive a compliment?

Haha I wasn't aware of the feature to share a program and view the program until this comment. Really cool feature and I think the confetti is fun, but I can imagine if the confetti should be removed. I don't feel very empowered to make this decision. 

About the example/demo programs, I think you are right! I saw your issue #1275 and totally agree. Maybe our team (team 13 Rocket scientists for the course Software Engineering at LIACS) could pick up this issue next week?

**Comment by fRedelaar** [comment]
> > **Edit** In extend to this suggestion. What do we want to do if a user runs an example program? They didn't do any work so should they receive a compliment?
> 
> I think this is a good point, shall we make a separate issue for that?

There already is I believe, #1275

**Comment by Felienne** [comment]
Lovely, that is a lot better!

**Review by Felienne — APPROVED** [review]

**Comment by TiBiBa** [comment]
> > A bit of topic: I just noticed that we are also getting compliments and the option to show confetti when viewing a shared program of another user. Is that expected behavior? Otherwise we should implement some check if we are currently in the code editor or just executing someone else's their code.
> > **Edit** In extend to this suggestion. What do we want to do if a user runs an example program? They didn't do any work so should they receive a compliment?
> 
> Haha I wasn't aware of the feature to share a program and view the program until this comment. Really cool feature and I think the confetti is fun, but I can imagine if the confetti should be removed. I don't feel very empowered to make this decision.
> 
> About the example/demo programs, I think you are right! I saw your issue #1275 and totally agree. Maybe our team (team 13 Rocket scientists for the course Software Engineering at LIACS) could pick up this issue next week?

Completely forgot I already made an issue about this. My bad! Sounds great if your group could pick this up next week.

**Comment by Felienne** [comment]
> > > **Edit** In extend to this suggestion. What do we want to do if a user runs an example program? They didn't do any work so should they receive a compliment?
> > 
> > 
> > I think this is a good point, shall we make a separate issue for that?
> 
> There already is I believe, #1275

Ah my bad, should have checked!

**Pull request merged**
