### PR TITLE
Translate Hedy keywords in Spanish. Issue #1527

### PR DESCRIPTION
**Pull request by Carlosbogo**
Created the file `es.yaml` with the translations for the Hedy keywords to Spanish as mentioned in #1527 .

### CODE REVIEW

**Comment by racertop** [comment]
Is it ok to translate two words to the same keyword? `at` translates to `en` and `in` also translates to `en`? Wouldn't that cause problems in the parser?

**Comment by Carlosbogo** [comment]
Oh right, sorry I didn't think about that.

They both translate to the same word, and right now I can't think of any other options for either of them. Should I try to specify the context in which each one is used?

**Comment by racertop** [comment]
> Oh right, sorry I didn't think about that.
> 
> They both translate to the same word, and right now I can't think of any other options for either of them. Should I try to specify the context in which each one is used?

Hi, thank you for your first contribution! Sorry I deleted the previous message to check for myself. And no, not a problem with `_AT` having the same translation as `_IN`, I tried your translation and it works! I thought it might lead to some problems but thankfully it doesn't. Great work :)

**Comment by Carlosbogo** [comment]
Oh great then. Glad to be of help!

**Comment by Felienne** [comment]
Duplicate words should not be a problem in most cases, we have one in En also (`add ... to ...` and `for i in range x to y` Those two TO's are different in the grammar but map to the same word.

Thanks for this work @Carlosbogo! I will look at in in depth later this week but on a first sight is looks great!

**Comment by Felienne** [comment]
Cool, I need to run a few scripts locally to enable everything, but here is a screenshot of the first ever program with es keywords!!

image

Syntax highlighting needs to be ran still but that will be added by me too!

**Comment by Felienne** [comment]
Tadaaaaa!!! 
image

Man I am pretty excited about this!!!! Very weird to see stuff in a lang you don't know haha. 

This will be live in a bit on [hedy-al](https://hedy-alpha.herokuapp.com/) (be sure to switch to espanol before trying it)

Once the school day finishes here I will deploy to the site!

One thing we do not yet know how to handle is example code! I guess we want to build something where you can see the examples in two langs but that is not ready yet...

**Comment by Felienne** [comment]
> Tadaaaaa!!! image
> 
> Man I am pretty excited about this!!!! Very weird to see stuff in a lang you don't know haha.
> 
> This will be live in a bit on [the test envl](https://hedy-alpha.herokuapp.com/) (be sure to switch to Espanol before trying it)
> 
> Once the school day finishes here I will deploy to the site!
> 
> One thing we do not yet know how to handle is example code! I guess we want to build something where you can see the examples in two langs but that is not ready yet...

haha oops forgot to swap one keyword! 
image


(but as you can see English keywords always work and you can mix them in if you want)

**Review by Felienne — APPROVED** [review]

**Comment by racertop** [comment]
> > Tadaaaaa!!! image
> > Man I am pretty excited about this!!!! Very weird to see stuff in a lang you don't know haha.
> > This will be live in a bit on [the test envl](https://hedy-alpha.herokuapp.com/) (be sure to switch to Espanol before trying it)
> > Once the school day finishes here I will deploy to the site!
> > One thing we do not yet know how to handle is example code! I guess we want to build something where you can see the examples in two langs but that is not ready yet...
> 
> haha oops forgot to swap one keyword! image
> 
> (but as you can see English keywords always work and you can mix them in if you want)

This is so cool!!!! I'll start using this to teach my niece in a bit :) So nice to see Hedy evolving so fast.

**Comment by eddieantonio** [comment]
Hey @Carlosbogo! I know this is super late, but I was just wondering why choose the infinitive versions of verbs (`imprimir`, `borrar`, `preguntar`, `girar`, `dormir`, `añadir`, `repetir`) when sometimes I feel the imperative reads better. For example,

```hedy
nombre es pregunte ¿Cómo te llamas?
imprime Hola nombre
```

I think this makes lots of sense for la tortuga:

```hedy
repita 4 veces
    gire 90
    adelante 50
```

For me personally, this reads more naturally than:

```hedy
nombre es preguntar ¿Cómo te llamas?
imprimir Hola nombre
```

```hedy
repetir 4 veces
    girar 90
    adelante 50
```

---

I think I ran into one issue — whether to use `tú` or `usted` — I chose to be polite! 😄

**Comment by racertop** [comment]
> Hey @Carlosbogo! I know this is super late, but I was just wondering why choose the infinitive versions of verbs (`imprimir`, `borrar`, `preguntar`, `girar`, `dormir`, `añadir`, `repetir`) when sometimes I feel the imperative reads better. For example,
> 
> ```
> nombre es pregunte ¿Cómo te llamas?
> imprime Hola nombre
> ```
> 
> I think this makes lots of sense for la tortuga:
> 
> ```
> repita 4 veces
>     gire 90
>     adelante 50
> ```
> 
> For me personally, this reads more naturally than:
> 
> ```
> nombre es preguntar ¿Cómo te llamas?
> imprimir Hola nombre
> ```
> 
> ```
> repetir 4 veces
>     girar 90
>     adelante 50
> ```
> 
> I think I ran into one issue — whether to use `tú` or `usted` — I chose to be polite! smile

Hi @eddieantonio! I understand what you're saying, but I agree with the way it is right now. `pregunta ¿Como te llamas?` reads as if we're telling someone in the computer to ask. I think the infinitive version is better since that reads as an action being done by the computer, which reflects more closely what's happening. In some other Spanish programming languages I've seen that's also how they translate the comamds, for example in [PSint](http://pseint.sourceforge.net) or in [Naspi](https://www.redalyc.org/pdf/784/78414496004.pdf) (a pseudocode used in my University).

Although I'd love to hear others inputs on this matter!

**Comment by eddieantonio** [comment]
> Hi @eddieantonio! I understand what you're saying, but I agree with the way it is right now. `pregunta ¿Como te llamas?` reads as if we're telling someone in the computer to ask. I think the infinitive version is better since that reads as an action being done by the computer, which reflects more closely what's happening. In some other Spanish programming languages I've seen that's also how they translate the comamds, for example in [PSint](http://pseint.sourceforge.net) or in [Naspi](https://www.redalyc.org/pdf/784/78414496004.pdf) (a pseudocode used in my University).
> 
> Although I'd love to hear others inputs on this matter!

Interesting! I did not know other Spanish PLs also use the infinitive -- thanks for the links! I wonder if what other languages that have an imperative mood will also make the same choice.

**Comment by Felienne** [comment]
Love this discussion folks! 

As a non-Spanish speaker it is hard for me to chime in but I love how much you are thinking about what is best here. I think looking at what other Spanish languages do makes a lot of sense and I am totally ok with that!

However, in Dutch, we do use the imperative for keywords. For `ask` f.e. we use `vraag` which is imperative, rather than `vragen` which is the infinitive. So like we are telling the computer what to do. But of course I don't know the exact feeling that imperative has in your language, it might feel different than in mine!

**Pull request merged**
