### PR TITLE
[FEATURE] Enables teachers to toggle developers mode and cheatsheet in customization

### LINKED ISSUE #1975: [UI idea] Add 'forced developer's mode' to class customization
**Idea incl level**
It would be nice if teachers could force their students to use developers mode. For example when working on an assignment /test for which they are not allowed to use the adventures for help. Together with this it would also be nice if teachers could hide/show the newly created cheatsheet button.

### LINKED ISSUE #2012: [UI idea] Enable teachers to hide cheatsheet
**Idea incl level**
With the increasing functionality of class customizations we support enforced developers mode #2004 and setting opening dates #2014. It would be nice if we also enable teacher to hide the cheatsheet if they want to. Together with the developers mode this creates an "exam mode" in which students can no longer use any help from the website.

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we add a small new feature that was already supported before the class customizations re-structuring. We re-implement the feature to enable teachers to enforce the developer's mode and toggle the visibility of the _cheatsheet_. This can be useful for an exam or to verify the students programming abilities as they are no longer able to get hints from the adventures or cheatsheet. It also increases the size of the  editor making it easier to create large programs.

**Fix for**
This PR fixes #1975 and fixed #2012.

**How to test**
Navigate to your class and notice the new UI of the customizations. Select the "mandatory developer's mode" and/or the "hide cheatsheet" and save the customizations. Verify that a student can only see the developers mode or cheatsheet when the corresponding setting is enabled.

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] Links to an existing issue or discussion (if not, create an issue first)
- [ ] Describes changes clear in the format above (present tense, no subject)
- [ ] Has a "how to test" section
- [ ] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

### CODE REVIEW

**Comment by TiBiBa** [comment]
Will add #2012 into this PR as well to prevent a rapidly growing list of open PR's. As #2012 is dependent on this work it should be fine.

**Comment by TiBiBa** [comment]
Fixed #2012 into this one! @MarleenGilsing can you maybe review this one as well?

**Comment by MarleenGilsing** [comment]
I see this, and it works great
image

I think I'm suppost to see another option with hide cheatsheet?

**Comment by TiBiBa** [comment]
> I see this, and it works great image
> 
> I think I'm suppost to see another option with hide cheatsheet?

Weird? Did you update the branch to the newest version? Commit 4136c9b should contain the newest functionality.

**Comment by MarleenGilsing** [comment]
My bad! Found it 😅

Works great! Maybe translate cheatsheet into spiekbriefje in Dutch?

**Comment by TiBiBa** [comment]
> My bad! Found it 😅
> 
> Works great! Maybe translate cheatsheet into spiekbriefje in Dutch?

Fixed!

**Review by Felienne — CHANGES_REQUESTED** [review]
Setting this to Request changes for the conflicts, mainly to keep track of the status of all PRs

**Comment by TiBiBa** [comment]
> Setting this to Request changes for the conflicts, mainly to keep track of the status of all PRs

Will attempt to fix this today, but the merge errors seem complex.

**Comment by Felienne** [comment]
Works like a charm!! (@OnnoEbbens will like this I think!)

**Review by Felienne — APPROVED** [review]

**Pull request merged**
