### PR TITLE
Translated Auth messages and some other pages in French

### PR DESCRIPTION
**Pull request by PatWg**
- Fixed typos and styling in `start-fr.md`
- Added articles to match the English page in `press-fr.md`
- Translated the contact form in `contact-fr.md`
- Translated the Auth messages. 

 
The Auth messages consistently use 'tu' (instead of 'vous' which is more formal), which I find to be more appropriate for kids. But it can be changed if necessary before this PR is merged.

### CODE REVIEW

**Comment by fpereiro** [comment]
Hi @PatWg ! This is fantastic work, thank you! I just checked out the code and the auth section is working well in French. Regarding the register, we use the informal you so your decision is aligned with what's already there :).

**Comment by fpereiro** [comment]
@Felienne there's a few more fields missing from the latest changes but I can add those as soon as we merge.

**Comment by PatWg** [comment]
Hi @fpereiro, @Felienne,

I haven't really checked if all the fields were there or not (compared to other languages like `en` or `nl`). I can check that and update the PR.

Or are you maybe mentioning the `Programs` section at the very end of the YAML file?

**Comment by Felienne** [comment]
@PatWg Yeah we just changed a bunch of things ourselves in the English version (f.e. the translation of dash for improved error messages) Do you want to double check yourself? @fpereiro can also do it if you prefer!

**Comment by PatWg** [comment]
Are you talking about the `HedyErrorMessages` category? I can see that there are a few issues with the translations in these messages. If that's what you had in mind, I can do that sure.

**Comment by Felienne** [comment]
> @Felienne @fpereiro Are you talking about the `HedyErrorMessages` category? I can see that there are a few issues with the translations in these messages. If that's what you had in mind, I can do that sure.

Yes that's the one! Would be great if you can pick that up!

**Comment by fpereiro** [comment]
Hi @PatWg and @Felienne  ! I just compared coursedata/texts/fr.yaml with another language and all the fields are there, only a few translations are missing:
- Some of HedyErrorMessages (lines 44-54)
- Programs (lines 126-137)

In an upcoming PR (https://github.com/Felienne/hedy/pull/200) we are adding another two phrases: "show explanation" and "hide explanation", but I can add the translation in that PR. @PatWg could you confirm that the following translations are correct? "montrer l'explication" and "cacher l'explication".

Thank you!

**Comment by PatWg** [comment]
Hi @fpereiro, @Felienne,

I've fixed the translations for `HedyErrorMessages` and `Programs`.

And yes @fpereiro, the French translations for show/hide explanation are correct.

**Comment by fpereiro** [comment]
Hi @PatWg . Thanks for adding the missing translations. It's all in there now!

**Review by fpereiro — APPROVED** [review]

**Pull request merged**
