### PR TITLE
Centralize keywords

### PR DESCRIPTION
**Pull request by Felienne**
This PR puts all symbols and all textual keywords in the first grammar file. That way we can potentially translate them all to Dutch or French or Swahili!

### CODE REVIEW

**Review by LauraTSD — COMMENTED** [review]
Centralized keywords are clear. I noticed that random was still in random : "random". Isn't this supposed to be _RANDOM = "random" now?

**Comment by Felienne** [comment]
> Centralized keywords are clear. I noticed that random was still in random : "random". Isn't this supposed to be _RANDOM = "random" now?

Great catch! Do you remember in what level you saw that?

**Comment by fpereiro** [comment]
This is amazing!!

**Comment by LauraTSD** [comment]
All of them :) From level 3 on I believe

**Comment by Felienne** [comment]
Superseded by #463

**Pull request closed without merging**
