### PR TITLE
Sublevels

### PR DESCRIPTION
**Pull request by Tazaria**
Issue #396 is also present here. That should be the only problem. Resolving issue #396 should result in this code passing all tests.

### CODE REVIEW

**Comment by fpereiro** [comment]
@Tazaria @Felienne just fixed the merge conflicts. It all looks good except for the failed unit tests.

**Comment by rix0rrr** [comment]
Hey! 

For whatever reason, over the course of this PR something changed in `hedyweb.py` that shouldn't have. Specifically, the argument called `loaded_program_name` has disappeared from `def render_assignment_editor()`.

Can you change:

```py
def render_assignment_editor(request, course, level_number, assignment_number, menu, translations, version, loaded_program, adventure_assignments, adventure_name):
```

into

```py
def render_assignment_editor(request, course, level_number, assignment_number, menu, translations, version, loaded_program, loaded_program_name, adventure_assignments, adventure_name):
```

?
Thanks!

**Comment by fpereiro** [comment]
@rix0rrr thank you for spotting that! I just applied the fix you mentioned. There still seems to be an issue with the tests for level 7-1.

**Comment by Felienne** [comment]
Hi all! Thanks for your hard work on this!

@Tazaria is the issue you are having in the tests this one: https://github.com/Felienne/hedy/issues/396

In that case you may comment the test out, because I will fix that in a separate branch.

**Comment by Tazaria** [comment]
Commented out the tests corresponding with issue #396. Everything should work now.

**Comment by fpereiro** [comment]
HI @Felienne @Tazaria -- just fixed the latest merge conflicts.

**Review by Felienne — APPROVED** [review]
Ziet er helemaal goed uit zo @Tazaria! Hij gaat nu naar alpha!

**Pull request merged**
