### PR TITLE
Introduce automated checks for PEP8-compliance using flake8

### PR DESCRIPTION
**Pull request by mennoliefstingh**
**Description**

This pull request serves as a first step towards making Hedy a PEP8-compliant project by introducing automatic linting of code using flake8. Flake8 is configured in setup.cfg, with a set max line length of 100 and an exclusion of rule F541 (f-strings without placeholders) for the tests folder. 

Two checks are added to the repository. First of all, it introduces a Git pre-commit hook that developers can install to automatically lint modified code on each commit. Secondly, it introduces a Github Actions workflow that lints the code on pushes and pull requests. It is possible to configure this Workflow such that failing the linting denies the pull request, but as that is outside the scope of issue 3377 I will make a new issue about making the entire codebase PEP8-compliant. 

Finally, CONTRIBUTING.md is updated with instructions for using the Git pre-commit hook, instructions for using autopep8 to automatically fix some issues and a friendly request to make sure all new or modified code is PEP8-compliant. 

**Fixes issue**
#3377 

**How to test**

To test the Git pre-commit hook, follow these commands:
``` 
pip install pre-commit
pre-commit install  # installs the pre-commit configuration from pre-commit-config.yml
```
After this, stage a commit with Python code and your commit will be prevented if your modifications fail the linting. You can force a commit by adding a `--no-verify` flag to your git commit. 

To test the Github action, simply push to the repository and visit the 'Actions' tab in Github: you should see the results of the linting in the workflow.

### CODE REVIEW

**Comment by mennoliefstingh** [comment]
additionally: include good documentation on pre-commit, including creating a bash file that installs the pre-commit hook automatically along with pip install -r requirements.txt

**Comment by Felienne** [comment]
As agreed in the meeting today, we will split this one in the pre-commit instruction and the workflow separately

**Comment by mennoliefstingh** [comment]
When writing the documentation I decided against including a bash script that runs pip install + pre-commit install in favor of writing about the (for now optional) pre-commit hook in the documentation. As the pre-commit blocks you from committing if your code doesn't adhere to guidelines (although you can force-commit) I think the only people who should be using it for now are people who understand what they're doing. This could change once we get the codebase to be pep8-compliant and want to enforce code styling on PR's.

**Comment by mennoliefstingh** [comment]
also, this PR still fails the PEP8 compliance Github Actions workflow but I actually removed that from the repository and disabled it in the github web interface so merging this PR won't actually introduce that workflow in the repository.

**Comment by Felienne** [comment]
> When writing the documentation I decided against including a bash script that runs pip install + pre-commit install in favor of writing about the (for now optional) pre-commit hook in the documentation. As the pre-commit blocks you from committing if your code doesn't adhere to guidelines (although you can force-commit) I think the only people who should be using it for now are people who understand what they're doing. This could change once we get the codebase to be pep8-compliant and want to enforce code styling on PR's.

Sounds reasonable!! I will try to look at this and merge it after the weekend!

**Comment by Felienne** [comment]
> also, this PR still fails the PEP8 compliance Github Actions workflow but I actually removed that from the repository and disabled it in the github web interface so merging this PR won't actually introduce that workflow in the repository.

Maybe a merge from main fixes this, let's see!

**Pull request merged**
